### ISSUE TITLE
wheel package format

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtpy#1]
Would it be possible to propose it in wheel package format on pypi ?

````
python setup.py sdist bdist_wheel --universal
twine upload dist/* 
````

**Comment by Nodd** [comment]
Is it useful since it's pure python ?

**Comment by goanpeca** [comment]
I just copied an issue from the old repo... 

Since it is pure python the wheel can be universal, so sure why not :+1:

**Comment by stonebig** [comment]
request:

````
python setup.py sdist bdist_wheel --universal
twine upload dist/* 
````

**Comment by goanpeca** [comment]
@stonebig will have it for later today, will ping you

**Comment by SylvainCorlay** [comment]
@goanpeca @stonebig I would rather add the `setup.cfg` to the root dir like in qtawesome. It could also be useful to add a RELEASE.md here as well.

**Comment by goanpeca** [comment]
Ok @SylvainCorlay
