### ISSUE TITLE
Random test failures on Debian infrastructure

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/qtpy#100]
Forwarding a [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854496) reported to me by Santiago Vila from the reproducible builds project. He has experienced some random test failures when building packages for `qtpy` multiple times on Debian.

Tests are run at build time for all supported Python versions, via a `python -m pytest tests` on their respective build trees wrapped by a call to `xvfb-run`. The builds succeed locally and on the [Debian builders](https://buildd.debian.org/status/package.php?p=python-qtpy) but fails on the [reproducibility builders](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/python-qtpy.html) with the following output:
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0

PyQt4: not installed
PyQt5: PyQt: 5.7 - Qt: 5.7.1
PySide: not installed

rootdir: /<<PKGBUILDDIR>>, inifile: 
collected 8 items

tests/test_main.py .
tests/test_patch_qcombobox.py ..
tests/test_patch_qheaderview.py .
tests/test_qtmultimedia.py .
tests/test_uic.py Aborted
```

Any idea where this could come from?

**Comment by ccordoba12** [comment]
Nop, sorry.

**Comment by ccordoba12** [comment]
Things should be working now.
