### ISSUE TITLE
module 'qtpy.QtGui' has no attribute 'QMainWindow'

### ISSUE THREAD

**Issue by junesun** [spyder-ide/qtpy#105]
When running the matplotlib example "embedding_in_qt4.py" 
(http://matplotlib.org/examples/user_interfaces/embedding_in_qt4.html#user-interfaces-embedding-in-qt4),I met the error as follows:
 
 File "embedding_in_qt4.py", line 80, in <module>
    class ApplicationWindow(QtGui.QMainWindow):
AttributeError: module 'qtpy.QtGui' has no attribute 'QMainWindow'

I have replaced the “PyQt4” by "qtpy" in the line "from qtpy import QtGui, QtCore"

**Comment by ccordoba12** [comment]
The right import is

    from qtpy import QtWidgets
    QtWidgets.QMainWindow

please read our Readme to read about how `qtpy` works.
