### ISSUE TITLE
Spurious cache files in PyPI tarball

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/qtpy#129]
Please take extra care with your future releases by ensuring they are done from a clean source tree. The current tarball on PyPI is riddled with cache files under `qtpy/tests`.

Thanks.

**Comment by ccordoba12** [comment]
Thanks @ghisvail, we'll fix this in 1.3.1

**Comment by rlaverde** [comment]
This could be fixing changing this MANIFEST.in line https://github.com/spyder-ide/qtpy/blob/master/MANIFEST.in#L5

`recursive-include qtpy/tests *`

`recursive-include qtpy/tests *.py`

**Comment by ccordoba12** [comment]
Great! Please open a PR about it.

**Comment by rlaverde** [comment]
I was wrong, after some testing I realize that is not the problem, I don't know what  the error could be, maybe we could add something like `find . -name '*.pyc' -delete` to the release instructions in the meanwhile 😞

**Comment by ghisvail** [comment]
You need a combination of both, i.e. a filter in MANIFEST.in which is restrictive enough, plus a release process which ensures that the tarball is generated from a clean environment. I can help for the former (PR to follow shortly), but the latter is in your hands.

**Comment by ccordoba12** [comment]
There's a git command that removes all files not under version control. I'll add it to our release notes to prevent this in the future.

**Comment by ghisvail** [comment]
> There's a git command that removes all files not under version control.

Indeed, a `git clean -fd` prior to running `python setup.py sdist` should be enough.

I'll update the Debian package with version `1.3.1` then.

**Comment by ccordoba12** [comment]
@ghisvail, I just released `1.3.1`.
