### ISSUE TITLE
Methods missing from QStandardPaths when QT_API=pyqt4

### ISSUE THREAD

**Issue by phargogh** [spyder-ide/qtpy#131]
Hi everyone, when I `pip install "qtpy>1.3"` and set `QT_API=pyqt4`, the only attributes available in the  `QtCore.QStandardPaths` module are the data attributes for the locations the class/enum `StandardLocation` and `displayName(...)`.  Other methods defined by QStandardPaths are missing, most notably the methods that are really helpful for transforming standard paths to actual paths such as `QtCore.QStandardPaths.writableLocation(...)`.

The temporary workaround is to `pip install "qtpy<1.3"`.

To reproduce, compare:
* `QT_API=pyqt4 python -c "from qtpy import QtCore; help(QtCore.QStandardPaths)"`
* `QT_API=pyqt5 python -c "from qtpy import QtCore; help(QtCore.QStandardPaths)"`

Thanks for all your work on `qtpy`!

**Comment by ccordoba12** [comment]
Sorry for this. Could you give us a list of all missing methods in PyQt4?

**Comment by rlaverde** [comment]
I think that methods aren't available in Qt4 at all. The `QStandardPaths` was part of `QDesktopServices`, but that methods/attributes that you mention were introduced in Qt5 

http://doc.qt.io/qt-4.8/qdesktopservices.html
http://doc.qt.io/qt-5/qdesktopservices-obsolete.html

**Comment by phargogh** [comment]
Yes, I realize that these methods/attributes were changed in the API migration from Qt4 to Qt5.

Here's my problem: I need to be able to access the CacheLocation path from both qt4 and qt5.  In qt4, this is via `QtGui.QDesktopServices.storageLocation()`.  In qt5, this is via `QtCore.QStandardPaths.writableLocation()`. 

With `qtpy<1.3`, the following code snippet works fine with either `QT_API=pyqt4` or `QT_API=pyqt5`:
```
try:                                                                                                                               
      # Qt4
    cache_dir = QtGui.QDesktopServices.storageLocation(
        QtGui.QDesktopServices.CacheLocation)
except AttributeError:
      # Package location changed in Qt5
    cache_dir = QtCore.QStandardPaths.writableLocation(
        QtCore.QStandardPaths.CacheLocation)
```

With `qtpy>=1.3`, the above code breaks, because `qtpy==1.3` [introduces a change](https://github.com/spyder-ide/qtpy/pull/112) that moves the `StandardLocation` enum to `QStandardPaths`.  It makes sense that the other methods in Qt4's `QDesktopServices` might not be moved, since the methods changed names in Qt5.  This would mean that I would still expect to be able to use `QDesktopServices.storageLocation`, just with `QtGui.QStandardPaths.CacheLocation` as the input.

Unfortunately, this expectation doesn't pan out:
```
$ QT_API=pyqt4 python -c "from qtpy import QtGui, QtCore; print QtGui.QDesktopServices.storageLocation(QtGui.QStandardPaths.CacheLocation)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class QDesktopServices has no attribute 'storageLocation'
```

OK, so then if `storageLocation` is no longer available from `QDesktopServices`, then I must be able to use `QtCore.QStandardPaths.writableLocation`.  Nope:
```
$ QT_API=pyqt4 python -c "from qtpy import QtGui, QtCore; print QtCore.QStandardPaths.writableLocation(QtCore.QStandardPaths.CacheLocation)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: class QStandardPaths has no attribute 'writableLocation'
```

I can still access `PyQt4.QtGui.QDesktopServices.storageLocation`, which is a workaround, but it would be nice to be able to actually use qtpy for this.

PS: Maybe this is as simple as re-exposing the missing methods from `QDesktopServices`?  The two missing methods are `storageLocation` and `displayName`.

Here's the `help()` for `qtpy.QtGui.QDesktopServices`:
```
>>> from qtpy import QtGui
>>> help(QtGui.QDesktopServices)
Help on class QDesktopServices in module qtpy.QtGui:

class QDesktopServices
 |  Data and other attributes defined here:
 |  
 |  openUrl = <built-in function openUrl>
 |      openUrl(QUrl) -> bool
 |  
 |  setUrlHandler = <built-in function setUrlHandler>
 |      setUrlHandler(QString, QObject, str)
 |      setUrlHandler(QString, Callable[..., None])
 |  
 |  unsetUrlHandler = <built-in function unsetUrlHandler>
 |      unsetUrlHandler(QString)
(END)
```

And here's the `help()` for `PyQt4.QtGui.QDesktopServices`:
```
>>> from PyQt4 import QtGui
>>> help(QtGui.QDesktopServices)
Help on class QDesktopServices in module PyQt4.QtGui:

class QDesktopServices(sip.simplewrapper)
 |  QDesktopServices()
 |  QDesktopServices(QDesktopServices)
 |  
 |  Method resolution order:
 |      QDesktopServices
 |      sip.simplewrapper
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  displayName(...)
 |      displayName(QDesktopServices.StandardLocation) -> QString
 |  
 |  openUrl(...)
 |      openUrl(QUrl) -> bool
 |  
 |  setUrlHandler(...)
 |      setUrlHandler(QString, QObject, str)
 |      setUrlHandler(QString, Callable[..., None])
 |  
 |  storageLocation(...)
 |      storageLocation(QDesktopServices.StandardLocation) -> QString
 |  
 |  unsetUrlHandler(...)
 |      unsetUrlHandler(QString)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  ApplicationsLocation = 3
 |  
 |  CacheLocation = 10
 |  
 |  DataLocation = 9
 |  
 |  DesktopLocation = 0
 |  
 |  DocumentsLocation = 1
 |  
 |  FontsLocation = 2
 |  
 |  HomeLocation = 8
 |  
 |  MoviesLocation = 5
 |  
 |  MusicLocation = 4
 |  
 |  PicturesLocation = 6
 |  
 |  StandardLocation = <class 'PyQt4.QtGui.StandardLocation'>
 |  
 |  
 |  TempLocation = 7
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from sip.simplewrapper:
 |  
 |  __init__(...)
 |      x.__init__(...) initializes x; see help(type(x)) for signature
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sip.simplewrapper:
 |  
 |  __dict__
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from sip.simplewrapper:
 |  
 |  __new__ = <built-in method __new__ of sip.wrappertype object>
 |      T.__new__(S, ...) -> a new object with type S, a subtype of T
(END)
```

**Comment by rlaverde** [comment]
I open a PR addressing the different problems:

> OK, so then if storageLocation is no longer available from QDesktopServices, then I must be able to use QtCore.QStandardPaths.writableLocation

Yes, this is a bug, I fixed it in the PR, you will be able to use `QtCore.QStandardPaths.writableLocation`

>PS: Maybe this is as simple as re-exposing the missing methods from QDesktopServices? The two missing methods are storageLocation and displayName.

I re-expose all the `QDesktopServices` old methods, and add a warning instead, although displayName should be available in `QtCore.QStandardPaths.displayName`

**Comment by phargogh** [comment]
Awesome, thanks so much!
