### ISSUE TITLE
QScintilla Support

### ISSUE THREAD

**Issue by daegontaven** [spyder-ide/qtpy#134]
I would appear that the Qsci python port in PyQt5 is not supported in QtPy. Is this because it is not supported yet on the other bindings ?

**Comment by ccordoba12** [comment]
Yes, that's the reason.

**Comment by dalthviz** [comment]
Just in case: https://bugreports.qt.io/browse/PYSIDE-1121

**Comment by dgoeries** [comment]
Since there was no movement over years, can't we include at least the Qt bindings in qtpy and keep this as known issue?
