### ISSUE TITLE
Add Wrapper for QtSql [feature request]

### ISSUE THREAD

**Issue by daniel-edler** [spyder-ide/qtpy#135]
I guess/hope the implementation for QtSql is pretty straight forward and similar to QtSvg. Thanks in advance.

**Comment by goanpeca** [comment]
@daniel-edler would you be interested in submitting a pull request?

**Comment by daniel-edler** [comment]
Sure, if you can wait a day

**Comment by goanpeca** [comment]
@daniel-edler we have all the time in the world :-), its sure request after all ;-)

**Comment by daniel-edler** [comment]
Sorry, but I'm a bit busy these days. Actually I "just" have to sync and start a pull request but first I have to read the instructions again. Once in a year (or two) isn't enough to remember the procedure
