### ISSUE TITLE
spyder is not a GUI builder at all

### ISSUE THREAD

**Issue by seedt8** [spyder-ide/qtpy#141]
I mean, seriously, guys? The world does not need another underfunded glorified vim or MS-DOS 2.0 "edlin.exe" , which spyder is, what pythonistas want is a true GUI builder, if you know what I am talking about.

If you deliver that, I will donate. But I do not need a vim+ and even donate tons of dough for that.

**Comment by CAM-Gerlach** [comment]
> spyder is not a GUI builder at all

Welcome to Github! You are exactly right, it's not one—it's a Scientific Python Development EnviRoment. Thanks for pointing that out.

**Comment by ccordoba12** [comment]
> what pythonistas want is a true GUI builder, if you know what I am talking about.

You could try TraitsUI or ipywidgets for that. Spyder is not meant to create scientific GUI interfaces.
