### ISSUE TITLE
On OSX qtpy applications are forcing discrete graphics

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtpy#142]
Based on https://github.com/ContinuumIO/anaconda-issues/issues/3679 it seems that even when using the `Supports Automatic Graphics Switching` Option as described on https://stackoverflow.com/questions/17893849/qml-causing-switch-to-discrete-graphics, the applications seem to switch to discrete GPU.

I created a test app on OSX based on a example.

## Using PyQt5
```python
# -*- coding: utf-8 -*-
"""
ZetCode PyQt5 tutorial

This example shows a tooltip on  a window and a button.

Author: Jan Bodnar
Website: zetcode.com
Last edited: August 2017
"""

# Standard library impors
import sys

# Third party imports
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QApplication, QPushButton, QToolTip, QWidget


class Example(QWidget):

    def __init__(self):
        super(Example, self).__init__()
        self.initUI()

    def initUI(self):
        QToolTip.setFont(QFont('SansSerif', 10))

        self.setToolTip('This is a <b>QWidget</b> widget')

        btn = QPushButton('Button', self)
        btn.setToolTip('This is a <b>QPushButton</b> widget')
        btn.resize(btn.sizeHint())
        btn.move(50, 50)

        self.setGeometry(300, 300, 300, 200)
        self.setWindowTitle('Tooltips')
        self.show()


def main():
    app = QApplication(sys.argv)
    app.ex = Example()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

<img width="1011" alt="screen shot 2018-04-17 at 09 43 18" src="https://user-images.githubusercontent.com/3627835/38877213-cd47820a-4223-11e8-9b80-fc2a08196f18.png">

## Using qtpy

```python
# -*- coding: utf-8 -*-
"""
ZetCode PyQt5 tutorial

This example shows a tooltip on  a window and a button.

Author: Jan Bodnar
Website: zetcode.com
Last edited: August 2017
"""

# Standard library impors
import sys

# Third party imports
from qtpy.QtGui import QFont
from qtpy.QtWidgets import QApplication, QPushButton, QToolTip, QWidget


class Example(QWidget):

    def __init__(self):
        super(Example, self).__init__()
        self.initUI()

    def initUI(self):
        QToolTip.setFont(QFont('SansSerif', 10))

        self.setToolTip('This is a <b>QWidget</b> widget')

        btn = QPushButton('Button', self)
        btn.setToolTip('This is a <b>QPushButton</b> widget')
        btn.resize(btn.sizeHint())
        btn.move(50, 50)

        self.setGeometry(300, 300, 300, 200)
        self.setWindowTitle('Tooltips')
        self.show()


def main():
    app = QApplication(sys.argv)
    app.ex = Example()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

Results in (Notice the **Requires High Perf GPU** Column)
<img width="1012" alt="screen shot 2018-04-17 at 09 44 22" src="https://user-images.githubusercontent.com/3627835/38877320-1043b8e4-4224-11e8-9a4c-2f79da2d4ca3.png">

This will affect any applications using `qtpy` on OSX, which results in higher energy consumption and hence decreasing battery life without need.

**Comment by mingwandroid** [comment]
After updating your info.plist did you remember to re-register it with the OS?

**Comment by goanpeca** [comment]
>After updating your info.plist did you remember to re-register it with the OS?

Nope, but for the test app I created I found what the issue was with qtpy

**Comment by mingwandroid** [comment]
Oh cool, what was it?

**Comment by goanpeca** [comment]
Quite simple https://github.com/spyder-ide/qtpy/pull/143/files

We were asking for the version on `PyQt5.Qt` which imports a lot of stuff (lazily I guess) but in that process it imports some modules that need the GPU and hence the whole app enters that mode until it quits.

Importing from `PyQt5.QtCore` instead of `PyQt5.Qt` solved the issue :-p

**Comment by mingwandroid** [comment]
Great, should probably load a lot faster too?

**Comment by ccordoba12** [comment]
> Great, should probably load a lot faster too?

Probably.

I'll release 1.4.1 with this fix later today or tomorrow.
