### ISSUE TITLE
Feature Request: PySide2 support

### ISSUE THREAD

**Issue by Skylion007** [spyder-ide/qtpy#15]
PySide has been forked to add Qt5 support so integration into PySide2 would prove very helpful for this project. It should be difficult either since PySide2 just uses 'PySide2' instead. In fact, someone might even be able to write a script to integrate it into the code easily: https://github.com/PySide/pyside2

**Comment by goanpeca** [comment]
Hi @Skylion007. According to https://github.com/PySide/pyside2/wiki/Project-Test-Status it is not ready so no point in supporting a half made port.

**Comment by Skylion007** [comment]
Fair enough, but I just want to have this port kept in mind for the future though.

**Comment by SylvainCorlay** [comment]
Let's keep this open then. The pyqt license is not as liberal as the one of pyside so it is a good thing to keep supporting the latter (even unofficially).

**Comment by goanpeca** [comment]
For reference https://wiki.qt.io/PySide2

**Comment by melevine** [comment]
PySide2 is quickly approaching a releasable state.  While the product might not be officially released, the API is fairly stable and support for the module structure should be straightforward.  It is also released in some major commercial products even in it's beta state.  Considering that will be the officially support python API from the Qt foundation, it would be nice to be ahead of the game and get support for it asap.  A lot of development needs to be done in anticipation of the release or use of certain Qt-based products.  Without support for PySide2, some developers are leaning towards other repos, like Qt.py, that already support the PySide2 API.

Also, considering PySide2 is/will be the officially supported Python API for Qt, it might be good to declare that the PySide2 API is the target module structure/API for QtPy.  It's a little unclear from the README what API QtPy presents and codes to.

**Comment by goanpeca** [comment]
Work is ready https://github.com/spyder-ide/qtpy/pull/84 but we need to wait for it to be officially released

**Comment by Nodd** [comment]
Why wait for the official release ?

**Comment by goanpeca** [comment]
To.. test it?
