### ISSUE TITLE
Shim PyQt5 ToPyDateTime for compatibility with PySide2

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/qtpy#153]
I fail on this problem:
- on PyQt5 we have QtCore.QDateTime.toPyDateTime()
- on PySide2 we have QtCore.QDateTime.toPython() 

==> Is it manageable in QtPy ? (making .QDateTime.toPyDateTime() redirect to .QDateTime.toPython(), when PySide2 ?

**Comment by stonebig** [comment]
same issue for PySide2.QtCore.QDateTime.toPyDate

seems to be also replaced per    .QDateTime.toPython()

**Comment by ccordoba12** [comment]
Yes, we can handle it. Please take a look at how we do it for `pyqtSignal`/`pyqtSlot`:

https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtCore.py#L18

**Comment by stonebig** [comment]
I may not have the needed skill to do it in a refined way. See my "hammer style" compatibility patch in guidata : https://github.com/PierreRaybaut/guidata/pull/46

**Comment by ccordoba12** [comment]
Ok, I'll do it.

**Comment by stonebig** [comment]
thanks.

**Comment by stonebig** [comment]
trying to make guiqwt compatible, I apply the same hammer patch on PythonQwt than on guidata, and I fall on a curious

"from qwt.qt.QtCore import Qt, QRect, QPoint, QT_VERSION"

==> my hammer technic it really not so perfect. I don't know if it's possible to salvage Pierre's legacy work.

**Comment by ccordoba12** [comment]
I think you should be better by:

* Forking Pierre's projects and maintain them yourself.
* Use qtpy instead of Pierre's own shim, so we can help you here with support for PySide2.

**Comment by stonebig** [comment]
thanks!
