### ISSUE TITLE
Spyder not working

### ISSUE THREAD

**Issue by samsri08** [spyder-ide/qtpy#164]
I have recently installed Anaconda on my system.
All other apps are working fine but spyder is not working.
When I open it a black window like this appears.
![image](https://user-images.githubusercontent.com/40247419/41373823-0c9cdf54-6f6f-11e8-9308-b2496775c247.png)

**Comment by ccordoba12** [comment]
This is not the right place to open this bug, this is:

https://github.com/spyder-ide/spyder/issues

So I'm closing it. Please reopen it there.
