### ISSUE TITLE
Maybe don't import PyQt5.Qt

### ISSUE THREAD

**Issue by altendky** [spyder-ide/qtpy#166]
https://github.com/spyder-ide/qtpy/blob/d53db43e11200ee9324f399504c8a97d2432658c/qtpy/tests/conftest.py#L38
(and other similar)

This imports all the modules including bluetooth which has issues on Win8.1 + PyQt5 >= 5.10 it seems.  Just using regular imports (`PyQt5.QtCore` for example) let's you not import bluetooth and avoid this.

Given that this is in a test file I don't obviously see the connection but I came here after having this issue myself and finding a couple other similar tickets referencing Spyder.

https://github.com/winpython/winpython/issues/592

https://stackoverflow.com/questions/48514027/spyder3-python-ide-does-not-start-this-windows-version-does-not-support-the-re/51549759#51549759

**Comment by ccordoba12** [comment]
> (and other similar)

That's the only one right now, and it's used in a pytest config file (so, not part of the package itself).

----

The problem you mention was fixed in PR #143, merged and released in our 1.4.1 version. Please update if you're using an older version.
