### ISSUE TITLE
Can't catch PythonQtError

### ISSUE THREAD

**Issue by astrofrog** [spyder-ide/qtpy#170]
I want to do something like:

```
try:
    import QtPy
except ImportError:
    pass
```

and have this also catch the case where PyQt5 or PySide aren't installed. However, in those cases the exception is ``PythonQtError`` rather than ``ImportError``. However, I can't catch ``PythonQtError`` because I can't do ``from qtpy import PythonQtError`` since QtPy won't import...

Since I don't watch to just catch ``Exception``, could ``PythonQtError`` be made a subclass of ``ImportError``?

**Comment by ccordoba12** [comment]
Sure, good idea. Please create a PR for this.

**Comment by ccordoba12** [comment]
I was not able to make it a subclass of ImportError because we use ImportError to go through all bindings and select one.

However, I'll inherit PythonQtError inherit from RuntimeError, which will make it easily catchable.

**Comment by astrofrog** [comment]
Sounds good, thanks!
