### ISSUE TITLE
Support for Qt3D

### ISSUE THREAD

**Issue by matthew-d-jones** [spyder-ide/qtpy#172]
I assume Qt3D is not wrapped as for PyQt5 the bindings are distributed as a separate package. Is this the case? Is there any plan to eventually wrap Qt3D or other separate components like QtDataVisualization?

**Comment by ccordoba12** [comment]
> Is there any plan to eventually wrap Qt3D or other separate components like QtDataVisualization?

There are no plans, but you're welcome to submit a PR to add those components. But are they supported by PySide2 besides PyQt5?

**Comment by matthew-d-jones** [comment]
Yes, both Qt3D and QtDataVisualization are supported by PySide2.

**Comment by ccordoba12** [comment]
Then please go ahead for it!

It's very simple, please take a look at pull request #157 to see how to do it.
