### ISSUE TITLE
Error when import QtCore.__version__ in PySide2

### ISSUE THREAD

**Issue by emcek** [spyder-ide/qtpy#178]
I think found small issue:
* pyqt5 - QtCore.QT_VERSION_STR
* pyqt4 - QtCore.QT_VERSION_STR
* pyside2 - PySide2.\_\_version\_\_
* pyside - PySide.\_\_version\_\_ (didn't check it)

So, it will work only form PyQt{4,5}:
``` python
from qtpy import QtCore
print(QtCore.__version__)
```
I belive in `qtpy.QtCore.py` in pyside sections we need import symbol from `PySide.__init__.py`

**Comment by emcek** [comment]
gui_test.py
``` python
from qtpy import QtCore
print('PyQt: {}'.format(QtCore.__version__))
```
with: `QT_API=pyqt5`:
```
PyQt: 5.11.2
```
with `QT_API=pyside2`:  
```
Traceback (most recent call last):
  File "/home/emc/gui_test.py", line 27, in <module>
    qtpy()
  File "/home/emc/gui_test.py", line 23, in qtpy
    print('PyQt: {}'.format(QtCore.__version__))
AttributeError: module 'qtpy.QtCore' has no attribute '__version__'
```
Because in PySide2:
``` python
import PySide2
print('PySide2.__version__', PySide2.__version__)
```
And in PyQt5:
``` python
from PyQt5 import QtCore
print('QtCore.QT_VERSION ', QtCore.QT_VERSION)
print('QtCore.PYQT_VERSION', QtCore.PYQT_VERSION)
print('QtCore.QT_VERSION_STR', QtCore.QT_VERSION_STR)
print('QtCore.PYQT_VERSION_STR', QtCore.PYQT_VERSION_STR)
```
Take a look:
https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtCore.py#L21
and:
https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtCore.py#L30

So basically qtpy/QtCore.py just add:
```python
from PySide2 import __version__
```
in PySide2 section

https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtCore.py#L103
NOTE: Not sure how it is in PySide, but probably same as in PySIde2

**Comment by ccordoba12** [comment]
Ok, I see. It should be an easy fix.

Would you like to submit a pull request?
