### ISSUE TITLE
QIntValidator left in QtWidgets, should be in QtGui

### ISSUE THREAD

**Issue by dracorpg** [spyder-ide/qtpy#18]
With PyQt4 or PySide as backend, QValidator and QDoubleValidator are properly imported when importing qtpy.QtGui / deleted when importing qtpy.QtWidgets. But the poor QIntValidator seems to have been left behind... I didn't check in detail but maybe other classes were forgotten too, since this was apparently a manual process?

**Comment by ccordoba12** [comment]
Yes, it was a manual process. If you can help us to detect more things that we've forgotten, that would be great!

In the meantime, I'm going to open a pull request to fix the QIntValidator thing :-)

**Comment by ccordoba12** [comment]
This should be fixed in pull request #19.
