### ISSUE TITLE
uic tools

### ISSUE THREAD

**Issue by hmaarrfk** [spyder-ide/qtpy#184]
I forget why, but I had to compile my uic files to python files.

I basically adapted the pyside2-tools and made them spit out `qtpy` everywhere.

I just wanted to cross post it here in case it is useful to anybody

https://github.com/hmaarrfk/qtpy-tools

Installable through conda-forge
https://anaconda.org/conda-forge/qtpy-uic

**Comment by ccordoba12** [comment]
Would you like to merge your work with qtpy or do you prefer to maintain it in a separate project?

**Comment by hmaarrfk** [comment]
unfortunately it is gpl license due to the liccense of the original work.

**Comment by hmaarrfk** [comment]
otherwise, i have no issues

**Comment by ccordoba12** [comment]
Ok, I see. Thanks for the info anyway, hopefully other people that follows this repo will find it useful.

**Comment by hmaarrfk** [comment]
yep, that was mostly my goal!
