### ISSUE TITLE
Binding Selection Logic

### ISSUE THREAD

**Issue by JasonGilholme** [spyder-ide/qtpy#192]
Hi,

In reference to [this section of code](https://github.com/spyder-ide/qtpy/blob/master/qtpy/__init__.py#L118), I was wondering what the reason is for the logic that makes the binding selection ignore the env var when a binding has already been imported.

In our situation, we're integrating tools into existing applications for the purpose of creating VFX.  These applications are built with Qt4/5, and some ship with python bindings - mostly PySide but some with PyQt.  Our tools are targeting PySide as that's an agreed upon industry standard and as such we've set the QT_API env var to be one of the pyside variants.

A problem arises however, when the host application ships with PyQt and imports it prior to our code importing qtpy.  The current behavior at the linked code ignores the env var in this case and falls back to using the lib that was already imported.

In our case, it's perfectly fine to have PySide2 co-existing with PyQt5 as our integrations aren't required to be parented to the PyQt5 widgets.

It's also worth noting that this need has come up through our use of qtawesome which implicitly uses qtpy as a shim layer.  The VFX industry has a defacto relationship with Qt.py to provide this behavior and we've subsequently made a patch to qtawesome to import Qt through that library for the time being.

This issue could be solved in either the qtawesome or the qtpy project, but I thought I'd start the discussion here as patching this logic seems like a smaller cut than trying to provide a shim for the shims in qtawesome.

Thanks,
Jase

**Comment by ccordoba12** [comment]
> A problem arises however, when the host application ships with PyQt and imports it prior to our code importing qtpy. The current behavior at the linked code ignores the env var in this case and falls back to using the lib that was already imported.

I don't understand your request very well. Do you want the same application to load and use both PySide and PyQt at the same time? Because that's precisely what qtpy is trying to avoid by using the already imported bindings instead of following QT_API.

> In our case, it's perfectly fine to have PySide2 co-existing with PyQt5 as our integrations aren't required to be parented to the PyQt5 widgets.

I don't understand what you mean by this. Could you explain it better?

> This issue could be solved in either the qtawesome

We're not going to change bindings in qtawesome to use Qt.py or to allow a sort of meta-shim to use either qtpy and Qt.py, if that's what you're suggesting here. That would make things really complex for us for no real gain.

> or the qtpy project

I don't understand how. I thought mixing PySide and PyQt widgets in the same app was not really possible.

**Comment by JasonGilholme** [comment]
Hey @ccordoba12,

In short, yes, we do need to be able to load PySide and PyQt in the same environment.

This works perfectly fine providing that they're both build against the same version of Qt, and you keep your PyQt references away from your PySide references.  I've attached a simple example to play with, but you'll need matching builds of PySide and PyQt to run it.

Regarding changes, I really just need to have some way of ensuring that qtpy will respect the QT_API environment variable, regardless of any existing imports of Qt bindings.  An additional environment variable perhaps?

Thanks,
Jase

```python

import sys

import PySide2.QtWidgets
import PyQt5.QtWidgets

app = PyQt5.QtWidgets.QApplication(sys.argv)

# Create a simple test window
mainWindow = PyQt5.QtWidgets.QMainWindow()
centralWidget = PyQt5.QtWidgets.QFrame(mainWindow)
centralWidget.setLayout(PyQt5.QtWidgets.QVBoxLayout())
mainWindow.setCentralWidget(centralWidget)
mainWindow.show()

# Use PyQt5 to find the window (naively), and add a label to the window
pyqtApp = PyQt5.QtWidgets.QApplication.instance()
pyqtWindow = pyqtApp.topLevelWidgets()[0]
pyqtLayout = pyqtWindow.centralWidget().layout()
pyqtWidget = PyQt5.QtWidgets.QLabel("From PyQt5!", pyqtWindow)
pyqtLayout.addWidget(pyqtWidget)

# The same code in PySide2
pysideApp = PySide2.QtWidgets.QApplication.instance()
pysideWindow = pysideApp.topLevelWidgets()[0]
pysideLayout = pysideWindow.centralWidget().layout()
pysideWidget = PySide2.QtWidgets.QLabel("From PySide!", pysideWindow)
pysideLayout.addWidget(pysideWidget)

sys.exit(app.exec_())
```

**Comment by ccordoba12** [comment]
Ok, thanks for explaining things better. Unfortunately we don't have time nor the need to address this, so pull requests are welcome to fix this.
