### ISSUE TITLE
QtWinExtras not supported

### ISSUE THREAD

**Issue by cherryleafroad** [spyder-ide/qtpy#193]
For example `from qtpy.QtWinExtras import QtWin`. This functionality would be very useful

https://doc.qt.io/qt-5/qtwinextras-index.html

**Comment by ccordoba12** [comment]
Please open a pull request and add it (it's really bery simple)- You can see previous pull requests to see how to do it, for instance #191.

**Comment by cherryleafroad** [comment]
Unfortunately don't have the time

**Comment by ccordoba12** [comment]
We neither, sorry.

**Comment by cherryleafroad** [comment]
That's ok. This is just here for future. Keeping a reference on things :) Thanks for your work and time :) Cheers

**Comment by dalthviz** [comment]
Fixed by #218
