### ISSUE TITLE
Missing QWebEngineProfile from QtWebEngineWidgets

### ISSUE THREAD

**Issue by johndoe46** [spyder-ide/qtpy#201]
Hello,

I'm trying substitute PySide2 with qtpy on an existing project, but apparently QWebEngineProfile is not here:

`ImportError: cannot import name 'QWebEngineProfile' from 'qtpy.QtWebEngineWidgets'` 

I guess it's all about this file: https://github.com/spyder-ide/qtpy/blob/master/qtpy/QtWebEngineWidgets.py#L20 ?

**Comment by ccordoba12** [comment]
Please add `QWebEngineProfile` to PYQT5 and PYSIDE2 in that file. That should be enough.

**Comment by ccordoba12** [comment]
I mean, please open a pull request with that change so we can merge it.
