### ISSUE TITLE
DeprecationWarning for getchildren

### ISSUE THREAD

**Issue by astrofrog** [spyder-ide/qtpy#206]
I'm running into a deprecation warning with PyQt5 5.14:

```
.../lib/python3.8/site-packages/qtpy/uic.py:184: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
     for custom_widget in custom_widgets.getchildren():
```

I guess the key here will be to figure out if it's safe to always iterate over ``custom_widgets`` directly or whether some older versions of PyQt and PySide need the explicit call to ``getchildren``.

**Comment by tirkarthi** [comment]
I have created #204 fixing this and another deprecation warning.

**Comment by goanpeca** [comment]
Thanks for working on this @tirkarthi added a comment over there.

**Comment by goanpeca** [comment]
@ccordoba12 is this a 1.x fix or a 2.x fix?
