### ISSUE TITLE
Seems qtpy not support windows flags in QtCore.Qt ?

### ISSUE THREAD

**Issue by luojunyuan** [spyder-ide/qtpy#210]
![image](https://user-images.githubusercontent.com/28323948/76920362-4796b200-6906-11ea-943a-8c40819ce217.png)

In the screenshot, pycharm can't recognize these flags but program goes well. 
use `from PyQt4.QtCore import Qt` is ok

And I have another question.
I'm using PyQt4.8 in my project. I use `QDeclarativeView` to create a qml windows. But in Qt5 it changed to `QQuickView` with another base class. But there is still a seem class named `QQuickWidget` in Qt5. Can qtpy make a binding to it?

Thanks!

**Comment by goanpeca** [comment]
@luojunyuan feel free to make a PR with the changes you suggest.

**Comment by luojunyuan** [comment]
oh, about the QtCore.Qt module I think it's a mistake made by PyCharm. Nothing wrong now
