### ISSUE TITLE
qtpy QtWebEngineWidgets fallback fails

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/qtpy#212]
There seems to be an issue when importing WebEngineWidgets using a remote desktop Win10 (off-topic, but anyone an idea?). While this is not qtpy related, the fallback import for qtpy also fails because `PyQt5.QtWebKitWidgets` seems to be missing consistently (tried on different machines) independently of the initial error.

```
 from qtpy import QtWebEngineWidgets
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
c:\program files\python\lib\site-packages\qtpy\QtWebEngineWidgets.py in <module>
     21     try:
---> 22         from PyQt5.QtWebEngineWidgets import QWebEnginePage
     23         from PyQt5.QtWebEngineWidgets import QWebEngineView

ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-03468c7324eb> in <module>
----> 1 from qtpy import QtWebEngineWidgets

c:\program files\python\lib\site-packages\qtpy\QtWebEngineWidgets.py in <module>
     24         from PyQt5.QtWebEngineWidgets import QWebEngineSettings
     25     except ImportError:
---> 26         from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
     27         from PyQt5.QtWebKitWidgets import QWebView as QWebEngineView
     28         from PyQt5.QtWebKit import QWebSettings as QWebEngineSettings

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by max3-2** [comment]
Ok this seems to be something deeper - I do see more and more windows installations where pyqt5 is missing the QtWebEngineWidgets. Installation is a simple pip installation - can someone confirm? 

The missing `PyQt5.QtWebKitWidgets` is ok since its deprecated for quite some versions now

**Comment by goanpeca** [comment]
Maybe you need to install https://pypi.org/project/PyQtWebEngine/ ?

**Comment by dalthviz** [comment]
Just in case, starting from PyQt5 5.12 you need to install `PyQtWebEngine` under a pip installation. Also, `PyQt5.QtWebKitWidgets` was removed in Qt 5.6
