### ISSUE TITLE
Fix CI / Remove older CI

### ISSUE THREAD

**Issue by srevinsaju** [spyder-ide/qtpy#213]
Hello
Great Project!!

I wanted to know if its possible to fix the CI or remove older / deprecated CI; Because the :x: near the commit, somehow makes it feel there are a lot of bugs in `qtpy`, while there might not be much errors.

(If you feel this is not an important issue to be discussed; feel free to close it. Thanks)

**Comment by goanpeca** [comment]
There is a PR moving everything to github actions.

https://github.com/spyder-ide/qtpy/pull/208

We just need to update it, but that will not happen for a few days.

**Comment by srevinsaju** [comment]
Hmm, ok; Thanks for the quick response
