### ISSUE TITLE
PyQt6 support

### ISSUE THREAD

**Issue by bgermann** [spyder-ide/qtpy#233]
Does `QtPy` support the newly released `PyQt6` package?

Related: #229

**Comment by stonebig** [comment]
I see an intersting metho in PyQtGraph, but I fail to apply it in QtPy context
https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/Qt.py#L331..L345

**Comment by stonebig** [comment]
PyQtGraph is pretty much leading the change https://github.com/pyqtgraph/pyqtgraph/pull/1707

**Comment by The-Compiler** [comment]
FWIW the easiest approach (and what I will do in [qutebrowser](https://qutebrowser.org/) is to:

- Don't support PyQt 6.0 (I need to wait for QtWebEngine to come back with Qt 6.2 anyways), thus no need for a shim like in https://github.com/pyqtgraph/pyqtgraph/pull/1707
- Switch all enum access to the scoped variants (I wrote a quick&dirty [script to do so](https://github.com/qutebrowser/qutebrowser/issues/5904#issuecomment-736792450))
- Drop support for PyQt5 < 5.11 (mid 2018) which only allowed unscoped enum access

From what I can tell, PySide2 has always allowed scoped access. PyQt5 5.10 and earlier hasn't, and neither has PyQt4 (not sure about the Qt4 PySide). But it's really time to drop those to be honest...

**Comment by j9ac9k** [comment]
pyqtgraph maintainer here; trying to maintain qt4 _and_ qt6 will be tough.  The enums namespace that PyQt6 requires I don't believe works for Qt4 bindings.  

In case it's helpful, here is where we do the bulk of our abstraction layer work (please keep in mind we don't support Qt4 any more): https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/Qt/__init__.py

**Comment by tlambert03** [comment]
Yeah, I'm all for @The-Compiler's proposal too.  Including dropping support for pre 5.11

**Comment by ccordoba12** [comment]
> pyqtgraph maintainer here; trying to maintain qt4 and qt6 will be tough. The enums namespace that PyQt6 requires I don't believe works for Qt4 bindings.

Hey @j9ac9k, thanks for chiming in! Ok, we'll remove support for PyQt4 before adding support for PyQt6/PySide6.

> Yeah, I'm all for @The-Compiler's proposal too. Including dropping support for pre 5.11

Ok, we'll take a look at that too.

**Comment by j9ac9k** [comment]
Regarding minimum Qt version to support; a frequent pain point we have had is that on the conda defaults channel; Qt 5.9 is what is distributed, so to make current versions of pyqtgraph work w/ conda dependents, `conda-forge` _must_ be installed.

That said, PySide2 < 5.11 was a real head ache to test for back when we technically supported it.  We eventually gave up, and made PySide2 be 5.12+.

**Comment by tlambert03** [comment]
> Qt 5.9 is what is distributed [on the default channel], so to make current versions of pyqtgraph work w/ conda dependents, conda-forge must be installed.

yeah, this issue comes up for us at napari a lot as well, though we also now only support ≥5.12 and try to help users navigate this annoyance in other ways.

**Comment by CAM-Gerlach** [comment]
> So we just need to add an upper constraint on QtPy 2.0 in our next version and keep it until Anaconda updates its packages.

Okay, I see—but wouldn't it be better to add `qt >=5.11` to the `run_constrained` of the conda recipe for QtPy 2.0.0+ to prevent it from being installed/upgraded in the presence of an unsupported Qt version, and resulting in a broken user environment? This would solve the issue not only for Spyder, but all of the other applications that depend on QtPy, both when being installed/updated in user environments that only have Qt <5.11 installed or available, and for those that don't (yet) support Qt >=5.11 in the first place. 

Also, constraining Spyder to not use QtPy 2.0 only affects future Spyder versions, unlike the previous, so broken environments/Spyder installs can still result by several potential avenues (if QtPy 2.0.0 goes live on `defaults` or `conda-forge` before the next Spyder version with that change, if Anaconda users install/update to any prior version, or if the solver selects Spyder 5.1.5 and QtPy 2.0.0 instead of Spyder 5.2.0 and QtPy 1.11.2, which are both equally valid possibilities). It would mean CF versions of Spyder cannot benefit from newer Qt/QtPy versions, and Spyder would conflict with any future CF package that required Qt6 or QtPy 2.0.0+. And that's just assuming only the CF version is constrained (which actually doesn't need to be at all); doing the constraint for all versions has even wider-reaching effects on numerous platforms that don't have this problem. Whereas, the former approach would avoid all of these issues. So unless I really misunderstand something, I'd highly recommend the former approach.

> Quansight is talking to them to see if the situation can be satisfactorily solved during the next months.

Okay; hopefully things work out with that.

> Sadly, Ray passed away several months ago.

Oh wow, I had no idea. That's really sad; he did so much for the community and I always enjoyed interacting with him.

**Comment by benoit-pierre** [comment]
It's not just `QApplication`, there's also `QMenu` and `QDialog`.

**Comment by kumattau** [comment]
I checked exec_ in PySide6. I think we add `exec_()` to the following object-types and value-types:

```
pyside-pyside-setup/sources/pyside6/PySide6$ grep -rE '<object-type name=|<value-type name=|add-function signature="exec_' . | grep -B1 'exec_'

./QtWidgets/typesystem_widgets_common.xml:  <object-type name="QDialog">
./QtWidgets/typesystem_widgets_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtWidgets/typesystem_widgets_common.xml:  <object-type name="QMenu">
./QtWidgets/typesystem_widgets_common.xml:    <add-function signature="exec_()" return-type="QAction*">
./QtWidgets/typesystem_widgets_common.xml:    <add-function signature="exec_(const QPoint&amp;,QAction* @action@ = nullptr)" return-type="QAction*">
./QtWidgets/typesystem_widgets_common.xml:    <add-function signature="exec_(QList&lt;QAction*>,const QPoint&amp;,QAction* @at@ = nullptr,QWidget* @parent@ = nullptr)" return-type="QAction*">
--
./QtWidgets/typesystem_widgets_common.xml:  <object-type name="QApplication">
./QtWidgets/typesystem_widgets_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtSql/typesystem_sql.xml:  <value-type name="QSqlDatabase">
./QtSql/typesystem_sql.xml:    <add-function signature="exec_(QString @query@ = QString())const" return-type="QSqlQuery">
./QtSql/typesystem_sql.xml:  <value-type name="QSqlQuery">
./QtSql/typesystem_sql.xml:    <add-function signature="exec_()" return-type="bool">
./QtSql/typesystem_sql.xml:    <add-function signature="exec_(const QString&amp;)" return-type="bool">
--
./QtSql/typesystem_sql.xml:  <object-type name="QSqlResult">
./QtSql/typesystem_sql.xml:      <add-function signature="exec_()" return-type="bool">
--
./QtPrintSupport/typesystem_printsupport_common.xml:  <object-type name="QPageSetupDialog">
./QtPrintSupport/typesystem_printsupport_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtPrintSupport/typesystem_printsupport_common.xml:  <object-type name="QPrintDialog">
./QtPrintSupport/typesystem_printsupport_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtGui/typesystem_gui_common.xml:  <object-type name="QDrag">
./QtGui/typesystem_gui_common.xml:    <add-function signature="exec_(QFlags&lt;Qt::DropAction&gt; @supportedActions@ = Qt::MoveAction)" return-type="Qt::DropAction">
./QtGui/typesystem_gui_common.xml:    <add-function signature="exec_(QFlags&lt;Qt::DropAction&gt;,Qt::DropAction)" return-type="Qt::DropAction">
--
./QtGui/typesystem_gui_common.xml:  <object-type name="QGuiApplication">
./QtGui/typesystem_gui_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtCore/typesystem_core_common.xml:  <object-type name="QThread">
./QtCore/typesystem_core_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtCore/typesystem_core_common.xml:  <object-type name="QEventLoop">
./QtCore/typesystem_core_common.xml:      <add-function signature="exec_(QFlags&lt;QEventLoop::ProcessEventsFlag> @flags@ = QEventLoop::AllEvents)" return-type="int">
--
./QtCore/typesystem_core_common.xml:  <object-type name="QCoreApplication">
./QtCore/typesystem_core_common.xml:    <add-function signature="exec_()" return-type="int">
--
./QtCore/typesystem_core_common.xml:  <value-type name="QTextStreamManipulator" default-constructor="QTextStreamManipulator(0, 0)">
./QtCore/typesystem_core_common.xml:    <add-function signature="exec_(QTextStream &amp;)">
```

**Comment by ccordoba12** [comment]
Answering to what @kumattau said above:

> I think we can simply assign exec to exec_ : QApplication.exec_ = QApplication.exec
> I checked exec_ in PySide6. I think we add exec_() to the following object-types and value-types

I agree with adding `exec_` to the objects that need it, so we can maintain compatibility with PyQt5/PySide2.

Could you help us to do that?

**Comment by dalthviz** [comment]
Also, after some discussion with @ccordoba12 we will try to support unscoped enums access in order to keep things working as if you were using PyQt5 (where scoped and unscoped access is available [at least from PyQt 5.9.2 + sip 4.9.13 with conda](https://github.com/spyder-ide/qtawesome/pull/179#issuecomment-950052489))

**Comment by j9ac9k** [comment]
> Also, after some discussion with @ccordoba12 we will try to support unscoped enums access in order to keep things working as if you were using PyQt5 (where scoped and unscoped access is available [at least from PyQt 5.9.2 + sip 4.9.13 with conda](https://github.com/spyder-ide/qtawesome/pull/179#issuecomment-950052489))

In case it helps, here is our logic we used to "promote" enums in PyQt6

https://github.com/pyqtgraph/pyqtgraph/blob/pyqtgraph-0.12.1/pyqtgraph/Qt.py#L331-L377

**Comment by kumattau** [comment]
Does QtPy supports Qt6/PyQt6/PySide6 Version 6.0 ?
I think, if QtPy supports 6.2 or later only, it is better that QtPy shows warning messages like as #284.

**Comment by CAM-Gerlach** [comment]
Seems like there was a clear consensus here for not supporting anything earlier than 6.2, so if @dalthviz agrees I can go ahead with a PR to also warn on those versions (the way I added it, it should be pretty straightforward to do without much code duplication).

**Comment by dalthviz** [comment]
Sounds good to me, thanks @kumattau for the feedback and @CAM-Gerlach for helping with the implementation :+1:

**Comment by CAM-Gerlach** [comment]
Thanks, opened as #294 

@dalthviz , just to check in, is there anything else specific we need for this issue?

**Comment by dalthviz** [comment]
> @dalthviz , just to check in, is there anything else specific we need for this issue?

I don't think so @CAM-Gerlach . Maybe #294 should close this :+1:

**Comment by CAM-Gerlach** [comment]
Okay, thanks! Let's hope it resolves this for good this time. :crossed_fingers:
