### ISSUE TITLE
Question about qtpy compatibility with PyQt5-5.15.4

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/qtpy#236]
Not reporting a bug, just a mystery!

Before I did a distribution upgrade from 20.10 which used python 3.8 to 21.04 which uses 3.9, qtpy and Spyder worked fine.  A couple of days later I launched Spyder for the first time since and experienced a qtpy exception.

To narrow down where exactly things went wrong, I copied the qtpy ```__init__.py``` into a user test program as-is.
The following statement is throwing an exception:
```from PyQt5.QtCore import PYQT_VERSION_STR as PYQT_VERSION```  # in ```__init__.py``` line 132 on github

Python package PyQt5 is installed in ```/usr/lib/python3/dist-packages/PyQt5/```.  There is no QtCore.py but there is a QtCore.pyi which does have a ```PYQT_VERSION_STR``` variable defined.  That was a surprise.

apt packages installed:
```
ii  pyqt5-dev                  5.15.4+dfsg-1  all          Development files for PyQt5
ii  pyqt5-dev-tools            5.15.4+dfsg-1  amd64        Development tools for PyQt5
un  python-pyqt5.qwt-doc       <none>         <none>       (no description available)
un  python-pyqtgraph-doc       <none>         <none>       (no description available)
ii  python3-pyqt5              5.15.4+dfsg-1  amd64        Python 3 bindings for Qt5
un  python3-pyqt5-dbg          <none>         <none>       (no description available)
un  python3-pyqt5.qsci         <none>         <none>       (no description available)
un  python3-pyqt5.qtchart      <none>         <none>       (no description available)
ii  python3-pyqt5.qtmultimedia 5.15.4+dfsg-1  amd64        Python 3 bindings for Qt5's Multimedia module
ii  python3-pyqt5.qtopengl     5.15.4+dfsg-1  amd64        Python 3 bindings for Qt5's OpenGL module
ii  python3-pyqt5.qtwebchannel 5.15.4+dfsg-1  amd64        Python 3 bindings for Qt5's WebChannel module
ii  python3-pyqt5.qtwebengine  5.15.4-1       amd64        Python 3 bindings for Qt5's WebEngine module
ii  python3-pyqt5.qwt          1.02.02-2      amd64        Python version of the Qwt6 technical widget library (Python3)
ii  python3-pyqt5.sip          12.8.1-1build1 amd64        runtime module for Python extensions using SIP
ii  python3-pyqtgraph          0.12.1-1       all          Scientific Graphics and GUI Library for Python 3
```

I saw that you lot are working on a 3.9 compatible version of Spyder which probably includes qtpy too.  Still on-going?

Any suggestions for a work-around in the meantime?  Thanks.

**Comment by stonebig** [comment]
QtPy has no special problem with Python-3.9, at least on Windows

**Comment by texadactyl** [comment]
@stonebig  Thanks.  You have some evidence that on Windows, with Python 3.9, PyQt5-5.12 works. All of the new Ubuntu 21.04 distros (ubuntu, xubuntu, lubuntu, gnome, etc.) use PyQt5-5.15.4.  So, this seems to be a qtpy / PyQt5-5.15.4 interface issue because of some restructuring.

I saw a note in another issue from @ccordoba12 that porting to Python 3.9 is on-going.  
Hopefully, this compatibility issue will be resolved soon so that I can start using Spyder again.

Note that I would try installing with```pip install PyQt5==5.12.3``` but this would cause side effects in Ubuntu 21.04 (very new) that I would like to avoid.

**Comment by texadactyl** [comment]
Happy ending of sorts although somewhat unrelated: I got ```miniconda``` (which always worked well with Spyder) to work well with our projects ```pip``` installs in a separate environment from base.  If something goes wrong in the future, I should be able to throw away that one environment without impact to the conda base.

In a perfect world, the scientists I work with would create conda packages but that's probably asking too much.

So, this is no longer an issue for me or the scientists I work with.
