### ISSUE TITLE
Compatibility with `QtWidgets.QOpenGLWidget` vs `QtOpenGLWidgets.QOpenGLWidget`

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#258]
I think we could keep this _(the new `QtOpenGLWidgets` module in `Qt6`)_ but we need to do also the compatibility import at `QtWidgets.py` in a similar fashion as done with `PySide6`: https://github.com/spyder-ide/qtpy/blob/32f4a9f9fd9df3758c5f779fdac17132b23acc37/qtpy/QtWidgets.py#L23

What do you think @ccordoba12 ?

_Originally posted by @dalthviz in https://github.com/spyder-ide/qtpy/pull/255#r731144977_

**Comment by ccordoba12** [comment]
I agree with adding the equivalent line for `PyQt6`. That's a good idea because it avoids us to add another module to `qtpy` (i.e. `QtOpenGLWidgets`) just for a single widget.
