### ISSUE TITLE
Add a deprecation warning for unsupported `Qt` versions and bindings (at least `Qt4`: `PyQt4` and `PySide`)

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#261]
Maybe could be worthy to release `1.11.3` with a depreciation warning:

- Deprecation warning for `Qt4` (removed `PyQt4` and `PySide` support for `v2.0.0`)
- Deprecation warning for older versions of `Qt5`: Depending on what minimum `Qt5` and bindings versions we will support for `v2.0.0`. Maybe `5.9` (if we can make it work), but most probably `5.12`

**Comment by ccordoba12** [comment]
> I think that sounds good, but lets wait to see what others think.

I agree with that message but not worded in third person. I mean, I think it's clearer and sounds better in second person:

```python
warnings.warn(
    "A deprecated Qt4-based binding (PyQt4/PySide) was installed, "
    "imported or set via the QT_API environment variable. "
    "To ensure your application is still supported in QtPy 2.0, "
    "please should ensure it doesn't depend upon, import or "
    "set the QT_API env var to 'pyqt', 'pyqt4' or 'pyside'.",
    DeprecationWarning,
)
```

**Comment by CAM-Gerlach** [comment]
Yup you're right @ccordoba12 , good point. I only had it that way before because we had different messages for developers and users, and since @dalthviz wanted to mainly target the former, I eliminated that part but didn't reword it.

Fixing an grammar/editing mistake,

```python
warnings.warn(
    "A deprecated Qt4-based binding (PyQt4/PySide) was installed, "
    "imported or set via the QT_API environment variable. "
    "To ensure your application is still supported in QtPy 2.0, "
    "please make sure it doesn't depend upon, import or "
    "set the QT_API env var to 'pyqt', 'pyqt4' or 'pyside'.",
    DeprecationWarning,
)
```

> Also @ccordoba12 you think that in the message we should add something regarding Qt5 ? (Like a minimum version)

:point_up: Since Qt bindings < 5.9-5.12 (per the discussion on #233 ) are also equally deprecated and no longer supported in QtPy 2.0, my suggestion was that we should also include those in this warning too.

**Comment by dalthviz** [comment]
> warnings.warn(
    "A deprecated Qt4-based binding (PyQt4/PySide) was installed, "
    "imported or set via the QT_API environment variable. "
    "To ensure your application is still supported in QtPy 2.0, "
    "please make sure it doesn't depend upon, import or "
    "set the QT_API env var to 'pyqt', 'pyqt4' or 'pyside'.",
    DeprecationWarning,
)

I think we can go with this message as it is @CAM-Gerlach

**Comment by dalthviz** [comment]
Hi @CAM-Gerlach any chance you can work on this with the last message? I think it could be nice to do the 1.11.3 release soon so if you have some time to work on this or if it is ok for someone else to work on this let us know

**Comment by CAM-Gerlach** [comment]
Sorry, this got lost in my queue somehow. Thanks for the reminder; I'll take care of it now.

One thing, though—this and #281 / #280 were all milestoned on 1.11.3, but #281 also bumped the QtPy 1.x version to 1.12. Was the latter intentional and we should rename the milestone, or is the former still correct? Thanks.

**Comment by ccordoba12** [comment]
> I think we can go with this message as it is @CAM-Gerlach

Agreed.

> Also @ccordoba12 you think that in the message we should add something regarding Qt5 ? (Like a minimum version)

I don't think so because `qtpy` takes care of that for the user.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Oh, so we already warn on Qt <5.6 and/or <5.9?

**Comment by ccordoba12** [comment]
> Oh, so we already warn on Qt <5.6 and/or <5.9?

No, we don't. Perhaps we should warn about Qt < 5.9 because the oldest version we can test.

**Comment by CAM-Gerlach** [comment]
That's what I was suggesting :smirk: But we could do that in another PR, since #283 should be ready to go and its a bit less trivial to code.

**Comment by dalthviz** [comment]
> One thing, though—this and #281 / #280 were all milestoned on 1.11.3, but #281 also bumped the QtPy 1.x version to 1.12. Was the latter intentional and we should rename the milestone, or is the former still correct? Thanks.

See https://github.com/spyder-ide/qtpy/pull/281#issuecomment-972950279

**Comment by dalthviz** [comment]
Checking again the comments, regarding the message for Qt 5 <5.9, that's going to be done by @CAM-Gerlach in a new PR, right? Should we reopen this issue and close it with the merge of that new PR?

**Comment by ccordoba12** [comment]
> regarding the message for Qt 5 <5.9

I think we should leave this message for QtPy 2.0

> Should we reopen this issue and close it with the merge of that new PR?

I'm not in favor of that. Instead, let's open a new issue and fix it with a new PR. This issue was about the Qt4 message.

**Comment by CAM-Gerlach** [comment]
> Instead, let's open a new issue and fix it with a new PR. 

That also makes the most sense to me :+1: . I can open a new issue.

> I think we should leave this message for QtPy 2.0

I'm not sure about that, but we can discuss that in the new issue. I'll try to compile the relevant bits from each of us there to get things started.

**Comment by CAM-Gerlach** [comment]
Sorry, took a while as I had to take some calls from family members, but opened as #284

**Comment by dalthviz** [comment]
Thanks @CAM-Gerlach , don't worry and hope everything is going ok

**Comment by CAM-Gerlach** [comment]
Yeah, thanks are going okay for now at the moment in that department, thanks :+1:
