### ISSUE TITLE
SignalInstance, Slot, and Property for Qt6 QtCore

### ISSUE THREAD

**Issue by tlambert03** [spyder-ide/qtpy#274]
I notice that `PyQt6.QtCore.pyqtBoundSignal`, `pyqtProperty`, and `pyqtSlot` were omitted from #225 and #229.  Any reason?  just lacking a PR to add them back?

**Comment by CAM-Gerlach** [comment]
Hey @tlambert03 , thanks for this! The reason would be that #225 and #229 are primarily focused on adding support for PySide6, while #233 is concerned with PyQt6 and mentions this issue (first pointed out by @tomgoddard ), and in fact PR #271 adds them back. Sorry if that wasn't clear!
