### ISSUE TITLE
PySide6 DeprecationWarning of exec_

### ISSUE THREAD

**Issue by kumattau** [spyder-ide/qtpy#286]
Hi, 

exec_ function is deprecated in PySide6, so the common PyQt5/PySide2 code gets deprecated warning when QT_API=pyside6.

```
DeprecationWarning: 'exec_' will be removed in the future. Use 'exec' instead.
  sys.exit(app.exec_())
```

On the other hand, PyQt6 removes exec_ but QtPy provides exec_ for the compatibility. (#259)
As a result, DeprecationWarning of exec_ occurs only when QT_API=pyside6.
Which should this DeprecationWarning be addressed by QtPy or the user application?
Note that print_ function of PySide6 may have the same problem.

**Comment by dalthviz** [comment]
Thanks for the feedback @kumattau ! I think that the warning should be handled by the user application although maybe we should provide the mapping for `exec_` and `print_` at some point for PySide6 as we do now for PyQt6 too

Just in case, what do you think @ccordoba12 @CAM-Gerlach ?

**Comment by ccordoba12** [comment]
I think we should handle the DeprecationWarning because we're the ones calling `exec_`.

**Comment by dalthviz** [comment]
> I think we should handle the DeprecationWarning because we're the ones calling exec_.

I think we are not actually calling  `exec_` but just mapping it (actually checking the mapping is only being done for PyQt6 currently). But just in case, @kumattau is the warning being generated when importing QtPy or when you in your code actually use `exec_`? Let us know

**Comment by kumattau** [comment]
@dalthviz,

I found this DeprecationWarning in qtawesome/icon_browswer.py

https://github.com/spyder-ide/qtawesome/blob/9602e1f3fd8a19cddc2165bf49909d95105d0667/qtawesome/icon_browser.py#L273

icon_browswer.py imports QtPy, but this warning is generated from PySide6 because QtPy does nothing about exec_ of PySide6.

**Comment by kumattau** [comment]
I think if this DeprecationWarning should be handled by user application, exec_ function in the user application needs to be changed to avoid this warning and support PyQt5/PyQt6/PySide2/PySide6.

```python
    # exec_ function is depricated in PySide6
    # Getting exec/exec_ and executing it is separated
    # because executing exec/exec_ may propagates any exceptions.
    try:
        app_exec = app.exec
    except AttributeError:
        app_exec = app.exec_
    sys.exit(app_exec())
```

**Comment by dalthviz** [comment]
Thanks for the clarification @kumattau ! I would say that then, with QtAwesome for example, we should do the corresponding changes there, but lets see what others say.

From the QtPy part then as, I was thinking, maybe we should a similar mapping for `exec` and `print` as is being done for PyQt6 but for PySide6

**Comment by CAM-Gerlach** [comment]
I agree with @dalthviz ; "handling" the warning in QtPy would mean either dropping the shim functionality (which we deliberately added knowing this), or silencing the warning, meaning downstream code (like QtAwesome) won't know it has to update and will just suddenly break someday, so either doesn't really make sense.

So, we can either simply pass the warning as we do now, or, if it doesn't raise backward compat concerns or have side effect on other users of the bindings (as in #26 ), map `exec_` and `print_` to their non-deprecated alternatives, with any necessary shim in between.

**Comment by kumattau** [comment]
Thank @dalthviz @CAM-Gerlach @ccordoba12 for comment and explanation.
I've acknowledged.
I sended the QtAwesome PR (https://github.com/spyder-ide/qtawesome/pull/186)  based on the discussion in this issue.

I think this issue can be closed.

**Comment by CAM-Gerlach** [comment]
> I think this issue can be closed.

As @dalthviz mentioned, we could consider aliasing the new names to the old ones, so user code doesn't need to implement try-excepts depending on the binding and version used; the goal of QtPy after all is a compatibility shim to abstract those differences so they don't need to be handled in every downstream application, and so ports to different bindings and upgrades to new versions is as seamless as possible (see #62 ).

**Comment by dalthviz** [comment]
> Thank @dalthviz @CAM-Gerlach @ccordoba12 for comment and explanation.
I've acknowledged.
I sended the QtAwesome PR (spyder-ide/qtawesome#186) based on the discussion in this issue.

Thanks @kumattau !!

> we could consider aliasing the new names to the old ones, so user code doesn't need to implement try-excepts depending on the binding and version used

Would you like to help us with that @kumattau ? Let us know!

**Comment by kumattau** [comment]
Thank @CAM-Gerlach @dalthviz for more explanations.

I'm sorry to misunderstand.

> we could consider aliasing the new names to the old ones, so user code doesn't need to implement try-excepts depending on the binding and version used

My current understanding is that, to be specific, user applications like as qtabrowser does not need to handle DeprecatedWarning of exec_/print_ functions of PySide6 because the future QtPy release will provide exec_/print_ functions of PySide6 which does not report DeprecatedWarning.

Is my understanding correct ?

I think the exec_/print_ functions is desirable to be provided in QtPy 2.0.0 release, which is going to support PySide6.

**Comment by dalthviz** [comment]
Yep that will be the idea :+1: The thing is that right now we are only doing the mapping on PyQt6. So we still need to add the mapping (some lines like for example `QApplication.exec_` = `QApplication.exec`) for PySide6, and I though that maybe that is something that you can help us doing @kumattau 

Sorry for not being so clear but let us know if you want to help with that or if you have any other question!

**Comment by kumattau** [comment]
> Note that print_ function of PySide6 may have the same problem.

I was mistaken about the `print_` function of PySide6.
Unlike exec_, PySide6/PySide2 **does not** have `print` function. They have `print_` function only.

The summary is as follows.

| Qt Bindings | PyQt5 | PyQt6 | PySide2 | PySide6    |
| ----------- | ----- | ----- | ------- | ---------- |
| exec_       | v     |       | v       | deprecated |
| exec        | v     | v     |         | v          |
| print_      | v     |       | v       | v          |
| print       | v     | v     |         |            |

I think QtPy don't have to do anything about `print` and `print_` of PySide6 because `print_` is available on PyQt5/PyQt6/PySide2/PySide6.

**Comment by kumattau** [comment]
I sent PR: #287 to fix this issue.

**Comment by CAM-Gerlach** [comment]
Thanks for your detailed research, @kumattau !
