### ISSUE TITLE
Qt6: QtCharts namespace incompatibility

### ISSUE THREAD

**Issue by thatfuckingbird** [spyder-ide/qtpy#304]
The QtCharts.QtCharts namespace was removed in Qt6, and the contents are now directly in the QtCharts module.
To preserve compatibility with Qt5 code, the below works:
```
qtpy.QtCharts.QtCharts = qtpy.QtCharts
```
Maybe this is worth adding in qtpy itself?

**Comment by dalthviz** [comment]
Hi @thatfuckingbird thank you for the feedback! I'm not totally sure (I guess that gives backwards compatibility with the QtPy 1.x handling that was being done) what do you think @ccordoba12 @CAM-Gerlach ?

**Comment by ccordoba12** [comment]
Yeah, I think it's a good idea to handle that change here.

**Comment by CAM-Gerlach** [comment]
Sounds good to me :+1:
