### ISSUE TITLE
Qt6: exec_ vs. exec

### ISSUE THREAD

**Issue by thatfuckingbird** [spyder-ide/qtpy#305]
Currently, qtpy does
```
QDialog.exec_ = QDialog.exec
```
for Qt6 to preserve the `exec_` function.
This leads to an error if I call `exec_` in a QDialog subclass, at least with PyQt6:
```
exec(self): first argument of unbound method must have type 'QDialog'
```

Instead, the below version works for subclasses too:
```
def  exec_( self, *args ):
  return self.exec( *args )

QDialog.exec_ = exec_
```

Same for QMenu, etc.

**Comment by dalthviz** [comment]
Thank you @thatfuckingbird for the feedback! Could you provide us a code example to check in our side? Let us know!

**Comment by kumattau** [comment]
> exec(self): first argument of unbound method must have type 'QDialog'

In PyQt6, all method aliases seem to have this problem.

```python
from qtpy.QtWidgets import QApplication
from qtpy.QtWidgets import QTextEdit

app = QApplication([])
obj = QTextEdit()
obj.setTabStopWidth(10) # QTextEdit.setTabStopDistance alias

# => TypeError: setTabStopDistance(self, float): first argument of unbound method must have type 'QTextEdit'
```
