### ISSUE TITLE
Qt6: missing unscoped enum values

### ISSUE THREAD

**Issue by thatfuckingbird** [spyder-ide/qtpy#306]
Using PyQt6 via qtpy, QtCore.Qt.BackButton is not defined. The equivalent QtCore.Qt.XButton1 is defined, however (both are defined in PyQt5).
These are in the Qt::MouseButton enum, and both values are present in both Qt5 and Qt6 according to the Qt docs.

**Comment by dalthviz** [comment]
Thank you again for the feedback @thatfuckingbird ! Indeed, there are some enum values that changed names that need adding an alias. Would you like to helps us with that? Let us know!

**Comment by thatfuckingbird** [comment]
To be clear, these did *not* change name in Qt itself.

e.g. Qt::BackButton is listed on both of these pages:

https://doc.qt.io/qt-6/qt.html
https://doc.qt.io/qt-5/qt.html

Qt::BackButton and Qt::ForwardButton are the only 2 I encountered, but there could be others. Now I suspect they are missing because Python Enums don't support duplicate values (?). In that case sadly I don't see how we could fix it.

**Comment by dalthviz** [comment]
At least for the unscoped access I think we could do some aliasing after promoting enums like this:

In `qtpy/QtCore.py` after the lines

```python
from .enums_compat import promote_enums
promote_enums(QtCore)
del QtCore
```

do

```python
Qt.BackButton = Qt.XButton1
Qt.ForwardButton = Qt.XButton2
```

**Comment by CAM-Gerlach** [comment]
> Now I suspect they are missing because Python Enums don't support duplicate values (?)

Only if you use the `@enum.unique` decorator on them. This should be fixable by upstream if so; did you try reporting it there?
