### ISSUE TITLE
`QtCore.Qt.mightBeRichText` undefined in PySide

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/qtpy#311]
it seems we have to define for Pyside6
` QtCore.Qt.mightBeRichText = QtGui.Qt.mightBeRichText `

![image](https://user-images.githubusercontent.com/4312421/147421999-edacd16b-7b47-4e66-9cf8-e05e09b7647e.png)

**Comment by dalthviz** [comment]
Hi @stonebig, would you like to work on this? Let is know!

**Comment by stonebig** [comment]
Failed at first attempts, if you can do it I would be glad
