### ISSUE TITLE
Remove `QHeaderView` patch

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#332]
Checking a little bit I think the current logic for the `QHeaderView` patch was done in order to give support to removed methods from PyQt4/PySide/Qt4 (https://github.com/spyder-ide/qtpy/issues/64 https://github.com/spyder-ide/qtpy/pull/65) and rigth now the test for the patch is being skipped in a good amount of testing setups since segfaults with Qt 5.15+  Qt6 and also with Python 3.7+ on MacOS

Taking this into account, maybe we should consider removing this patch logic? What do you think @ccordoba12 @CAM-Gerlach ?

**Comment by ccordoba12** [comment]
I agree with that.

**Comment by CAM-Gerlach** [comment]
I agree as well; #26 offered a fairly compelling rationale to avoid these sorts of matches.
