### ISSUE TITLE
Segfaulting tests on PyQt6 + Windows on both Py3.7 and 3.10 (no conda) probably due to PyQt 6.3.0 

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#336]
Looks like the tests started segfaulting on PyQt6 + Windows on both Py3.7 and 3.10 (no conda). Based on the check logs, it seems likely this is due to the PyQt PyPI wheels for Qt 6.3.0 being released; any idea on fixing this from our end, or should we pin to qt 6.2.x for now?

_Originally posted by @CAM-Gerlach in https://github.com/spyder-ide/qtpy/issues/334#issuecomment-1100450351_

**Comment by dalthviz** [comment]
Seems like we where installing PyQt6 6.2.3 with PyQt6-Qt6 6.3.0 so a DLL error was being raised.

**Comment by CAM-Gerlach** [comment]
Ah, I thought that was supported like it is with e.g. PySide on conda, but evidently not, and presumably for whatever reason PyQt doesn't constrain `PyQt-Qt` to a compatible version (which it should, especially if it causes a segfault)...
