### ISSUE TITLE
del some names in QtCore ?

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/qtpy#35]
In `QtCore.py` a few variables are renamed but the old names still persist, like `pyqtSignal` and `Signal`. PyQt variants should be removed.
(PyQt variants are imported by `import *`)

**Comment by ccordoba12** [comment]
+1 to this. PR coming? ;-)

**Comment by Nodd** [comment]
Maybe after #33 :oP

**Comment by goanpeca** [comment]
Should we "manually" import all items? instead of * and deleting? (yes more work but also more explicit)

**Comment by Nodd** [comment]
It would help for autocompletion.
If we do this, there should be one item per line, so that later modifications show clearly what is modified. That's the theory, maybe having too many lines will hurt more than help.

**Comment by goanpeca** [comment]
:-)
