### ISSUE TITLE
Simplify QtCore.py

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/qtpy#36]
There is some coe like:
```python
    from PyQt4.QtCore import *
    from PyQt4.QtCore import QCoreApplication
```
Why is the secon line needed, since `import *` is supposed to have imported `QCoreApplication` already ?

**Comment by ccordoba12** [comment]
Those are things we inherited from Spyder that fix crazy crashes under some specific situations.

I think it's better to leave it.

**Comment by Nodd** [comment]
In this case a comment is needed, otherwise it'll disappear sometimes...
