### ISSUE TITLE
Additions needed for PySide6 support (`QFontMetricsF.width`, `QLineEdit.getTextMargins` and `QtWidgets.QUndoCommand`)

### ISSUE THREAD

**Issue by random-developer** [spyder-ide/qtpy#365]
I recently ported pycode to support PySide6, including removing the pyqode.qt compatibility module and using qtpy instead. To complete that, I needed to add some additional support:

```
import os
from qtpy import PYSIDE6_API
qt_api = os.environ['QT_API'].lower()
if qt_api in PYSIDE6_API:
    from PySide6.QtGui import *
    from PySide6.QtWidgets import *
    QFontMetrics.width = lambda self, *args, **kwargs: self.horizontalAdvance(*args, **kwargs)
    QFontMetricsF.width = lambda self, *args, **kwargs: self.horizontalAdvance(*args, **kwargs)
    QLineEdit.getTextMargins = lambda self: (self.textMargins().left(), self.textMargins().top(), self.textMargins().right(), self.textMargins().bottom())
```

Additionally I needed to add in a single source file (I didn't modify my qtpy files at all):

```
try:
    from qtpy import QtGui
    QtWidgets.QUndoCommand = QtGui.QUndoCommand
except:
    pass
```

**Comment by random-developer** [comment]
Hi @dalthviz, I don't know if there's a specific version of PySide6 where this becomes necessary. (I happen to be using 6.3.1 and have only previously used PyQt5.)

I've never created a GitHub PR before but I'll give it a shot with these changes!

**Comment by dalthviz** [comment]
Thanks @random-developer ! Regarding how to contribute, you can check our contributing guide at https://github.com/spyder-ide/qtpy/blob/master/CONTRIBUTING.md (basically you need to create a fork from this repo into your account and then work from a branch on your fork which you then will use to submit a PR using the GitHub interface)

Also, if this changes help with the latest PySide6 (6.3.1) then I would say that  is good to have them :+1:

If you need any further guidance let us know!
