### ISSUE TITLE
mypy wrong class operators

### ISSUE THREAD

**Issue by hiaselhans** [spyder-ide/qtpy#385]
In this reproducer:

``` python
from qtpy import QtCore
#from PySide6 import QtCore

a=QtCore.QSize(200, 200)

b = a / 2
c = a * 0.5
```
Mypy fails to get the (not-inplace) multiplication and division annotations right
Inplace multiplication annotations (a *= 0.5) work

``` bash
$ QT_API=pyside6 mypy $(qtpy mypy-args) reproducer.py 
reproducer.py:6: error: Too few arguments for "__truediv__" of "QSize"  [call-arg]
reproducer.py:6: error: Unsupported operand types for / ("QSize" and "int")  [operator]
reproducer.py:7: error: No overload variant of "__mul__" of "QSize" matches argument type "float"  [operator]
reproducer.py:7: note: Possible overload variants:
reproducer.py:7: note:     def __mul__(self, QSize, float) -> QSize
reproducer.py:7: note:     def __mul__(self, float, QSize) -> QSize
Found 3 errors in 1 file (checked 1 source file)
```

while using pyside6 directly works without problem:

``` bash
$ mypy reproducer.py 
Success: no issues found in 1 source file
```

**Comment by dalthviz** [comment]
Hi @hiaselhans thank you for the feedback! I tested this on Windows and in both cases (with `qtpy` or directly importing from `PySide6`) I got: `reproducer.py:6: error: Unsupported operand types for / ("QSize" and "int")`

Could be possible for you to give us more info about your setup to try to reproduce this (OS, packages versions, etc )? Let us know!

**Comment by dalthviz** [comment]
Thanks for giving this a check @StSav012 ! I think too that there is not much we can do from the QtPy side but I will let this open just in case someone is able to reproduce or the OP post more info in the future

**Comment by CAM-Gerlach** [comment]
Since it's been over three months with no response from the OP, and it seems from our testing and what others have confirmed, it appears this isn't a QtPy bug and there isn't much we can do about it, maybe it makes sense to leave it closed for now, and we can always re-open it if someone is able to reproduce it or more info emerges?

**Comment by hiaselhans** [comment]
Hi,

I just tested the reproducer again and it seems like all typings are correct now. In both pyside6 and qtpy

Thanks! And sorry i missed the first answer.

**Comment by CAM-Gerlach** [comment]
Great, thanks @hiaselhans ! Glad to hear!
