### ISSUE TITLE
Error executing .py generated from .ui file - `ImportError: DLL load failed while importing QtCore`

### ISSUE THREAD

**Issue by Savita-Panwar** [spyder-ide/qtpy#388]
Please help with an error. After converting my .ui file to .py file, while i was executing .py the following error is appearing:
```
from PyQt5 import QtCore, QtGui, QtWidgets ImportError: DLL load failed while importing QtCore: The specified module could not be found. 
```

While it got perfectly executed first time but not on second time.

**Comment by dalthviz** [comment]
Hi @Savita-Panwar , could you describe step by step how this issue is happening to you? Also, could you share your .ui and .py files? Checking the traceback seems like you have an error related with your `PyQt5` installation (it being unable to find `QtCore`) and no mention to QtPy. Is that the full traceback you are getting?

Without further information there is not much we can do besides suggesting you to reinstall PyQt5, sorry :/

**Comment by Savita-Panwar** [comment]
Thanks dalthviz, I was able to run the program once while trying it second time had shown the error. Then I installed the latest version of Python, Anaconda and the required files. And got it sorted. You are right it might be because of Qtcore.

**Comment by dalthviz** [comment]
Thank you for letting us know! I will close this then as not related with QtPy then :+1:

**Comment by CAM-Gerlach** [comment]
(Re-closing with the appropriate close mode for an invalid issue)

**Comment by Savita-Panwar** [comment]
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openac.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tkinter.filedialog import askopenfilename
import os
import sys
from tkinter import messagebox

#import QtWidgets as QtWidgets
import mysql
from PIL import  Image,ImageTk
from tkinter.filedialog import askopenfilename
import tkcalendar as tkcalendar
from database_details import *
from company_details import *
import mysql.connector as con1

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(884, 631)
        self.comboBox_AccountType = QtWidgets.QComboBox(Form)
        self.comboBox_AccountType.setGeometry(QtCore.QRect(210, 60, 251, 22))
        self.comboBox_AccountType.setStyleSheet("font: 87 10pt \"Segoe
UI Black\";")
        self.comboBox_AccountType.setObjectName("comboBox_AccountType")
        self.comboBox_AccountType.addItem("Sale")
        self.comboBox_AccountType.addItem("Purchase")
        self.comboBox_AccountType.addItem("Nominal")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(90, 60, 101, 21))
        self.label1.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label1.setObjectName("label1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 91, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Account_Name = QtWidgets.QLineEdit(Form)
        self.lineEdit_Account_Name.setGeometry(QtCore.QRect(210, 90, 251, 22))
        self.lineEdit_Account_Name.setObjectName("lineEdit_Account_Name")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 120, 53, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2_AddressLine1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2_AddressLine1.setGeometry(QtCore.QRect(210,
120, 113, 22))
        self.lineEdit_2_AddressLine1.setObjectName("lineEdit_2_AddressLine1")
        self.lineEdit_3_AddressLine2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3_AddressLine2.setGeometry(QtCore.QRect(210,
150, 113, 22))
        self.lineEdit_3_AddressLine2.setObjectName("lineEdit_3_AddressLine2")
        self.lineEdit_4_AddressLine3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4_AddressLine3.setGeometry(QtCore.QRect(210,
180, 113, 22))
        self.lineEdit_4_AddressLine3.setStyleSheet("font: 75 10pt
\"Segoe UI Semibold\";")
        self.lineEdit_4_AddressLine3.setObjectName("lineEdit_4_AddressLine3")
        self.lineEdit_5_Postcode = QtWidgets.QLineEdit(Form)
        self.lineEdit_5_Postcode.setGeometry(QtCore.QRect(210, 210, 113, 22))
        self.lineEdit_5_Postcode.setStyleSheet("bold")
        self.lineEdit_5_Postcode.setObjectName("lineEdit_5_Postcode")
        self.label_4_Postcode = QtWidgets.QLabel(Form)
        self.label_4_Postcode.setGeometry(QtCore.QRect(90, 210, 53, 16))
        self.label_4_Postcode.setObjectName("label_4_Postcode")
        self.label_5_Contact_Name = QtWidgets.QLabel(Form)
        self.label_5_Contact_Name.setGeometry(QtCore.QRect(90, 240, 91, 16))
        self.label_5_Contact_Name.setObjectName("label_5_Contact_Name")
        self.lineEdit_6_Contact_Name = QtWidgets.QLineEdit(Form)
        self.lineEdit_6_Contact_Name.setGeometry(QtCore.QRect(210,
240, 113, 22))
        self.lineEdit_6_Contact_Name.setObjectName("lineEdit_6_Contact_Name")
        self.label_6_Discount = QtWidgets.QLabel(Form)
        self.label_6_Discount.setGeometry(QtCore.QRect(90, 270, 81, 16))
        self.label_6_Discount.setObjectName("label_6_Discount")
        self.lineEdit_7_Discount = QtWidgets.QLineEdit(Form)
        self.lineEdit_7_Discount.setGeometry(QtCore.QRect(210, 270, 113, 22))
        self.lineEdit_7_Discount.setObjectName("lineEdit_7_Discount")
        self.label_7_ACCode = QtWidgets.QLabel(Form)
        self.label_7_ACCode.setGeometry(QtCore.QRect(90, 300, 53, 16))
        self.label_7_ACCode.setObjectName("label_7_ACCode")
        self.lineEdit_8_ACCode = QtWidgets.QLineEdit(Form)
        self.lineEdit_8_ACCode.setGeometry(QtCore.QRect(210, 300, 113, 22))
        self.lineEdit_8_ACCode.setObjectName("lineEdit_8_ACCode")
        self.label_8_Phone = QtWidgets.QLabel(Form)
        self.label_8_Phone.setGeometry(QtCore.QRect(480, 60, 53, 16))
        self.label_8_Phone.setObjectName("label_8_Phone")
        self.lineEdit_9_Phone1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9_Phone1.setGeometry(QtCore.QRect(610, 60, 113, 22))
        self.lineEdit_9_Phone1.setObjectName("lineEdit_9_Phone1")
        self.lineEdit_10_Phone2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10_Phone2.setGeometry(QtCore.QRect(610, 90, 113, 22))
        self.lineEdit_10_Phone2.setObjectName("lineEdit_10_Phone2")
        self.label_9_Fax = QtWidgets.QLabel(Form)
        self.label_9_Fax.setGeometry(QtCore.QRect(480, 120, 53, 16))
        self.label_9_Fax.setObjectName("label_9_Fax")
        self.lineEdit_11_Fax = QtWidgets.QLineEdit(Form)
        self.lineEdit_11_Fax.setGeometry(QtCore.QRect(610, 120, 113, 22))
        self.lineEdit_11_Fax.setObjectName("lineEdit_11_Fax")
        self.label_10_EmailAddress = QtWidgets.QLabel(Form)
        self.label_10_EmailAddress.setGeometry(QtCore.QRect(480, 150, 91, 16))
        self.label_10_EmailAddress.setObjectName("label_10_EmailAddress")
        self.lineEdit_12_EmailAddress = QtWidgets.QLineEdit(Form)
        self.lineEdit_12_EmailAddress.setGeometry(QtCore.QRect(610,
150, 113, 22))
        self.lineEdit_12_EmailAddress.setObjectName("lineEdit_12_EmailAddress")
        self.label_11_FuelCharge = QtWidgets.QLabel(Form)
        self.label_11_FuelCharge.setGeometry(QtCore.QRect(480, 180, 91, 16))
        self.label_11_FuelCharge.setObjectName("label_11_FuelCharge")
        self.lineEdit_13_FuelCharge = QtWidgets.QLineEdit(Form)
        self.lineEdit_13_FuelCharge.setGeometry(QtCore.QRect(610, 180, 113, 22))
        self.lineEdit_13_FuelCharge.setObjectName("lineEdit_13_FuelCharge")
        self.label_12_PaymentTerms = QtWidgets.QLabel(Form)
        self.label_12_PaymentTerms.setGeometry(QtCore.QRect(480, 210, 91, 16))
        self.label_12_PaymentTerms.setObjectName("label_12_PaymentTerms")
        self.label_13_VAT_RegNo = QtWidgets.QLabel(Form)
        self.label_13_VAT_RegNo.setGeometry(QtCore.QRect(480, 240, 91, 16))
        self.label_13_VAT_RegNo.setObjectName("label_13_VAT_RegNo")
        self.lineEdit_14_PaymentTerms = QtWidgets.QLineEdit(Form)
        self.lineEdit_14_PaymentTerms.setGeometry(QtCore.QRect(610,
210, 113, 22))
        self.lineEdit_14_PaymentTerms.setObjectName("lineEdit_14_PaymentTerms")
        self.lineEdit_15_VAT_RegNo = QtWidgets.QLineEdit(Form)
        self.lineEdit_15_VAT_RegNo.setGeometry(QtCore.QRect(610, 240, 113, 22))
        self.lineEdit_15_VAT_RegNo.setObjectName("lineEdit_15_VAT_RegNo")
        self.label_14_Notes = QtWidgets.QLabel(Form)
        self.label_14_Notes.setGeometry(QtCore.QRect(480, 270, 53, 16))
        self.label_14_Notes.setObjectName("label_14_Notes")
        self.textEdit_Notes = QtWidgets.QTextEdit(Form)
        self.textEdit_Notes.setGeometry(QtCore.QRect(610, 270, 211, 87))
        self.textEdit_Notes.setObjectName("textEdit_Notes")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(480, 370, 121, 16))
        self.label_15.setObjectName("label_15")
        self.comboBox_2_D_N_AC = QtWidgets.QComboBox(Form)
        self.comboBox_2_D_N_AC.setGeometry(QtCore.QRect(610, 370, 121, 22))
        self.comboBox_2_D_N_AC.setObjectName("comboBox_2_D_N_AC")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(480, 400, 71, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_3_PriceCode = QtWidgets.QComboBox(Form)
        self.comboBox_3_PriceCode.setGeometry(QtCore.QRect(610, 400, 73, 22))
        self.comboBox_3_PriceCode.setObjectName("comboBox_3_PriceCode")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(690, 400, 81, 16))
        self.label_17.setObjectName("label_17")
        self.comboBox_4_AcType = QtWidgets.QComboBox(Form)
        self.comboBox_4_AcType.setGeometry(QtCore.QRect(770, 400, 73, 22))
        self.comboBox_4_AcType.setObjectName("comboBox_4_AcType")


        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(480, 430, 71, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_16_RoundNo = QtWidgets.QLineEdit(Form)
        self.lineEdit_16_RoundNo.setGeometry(QtCore.QRect(610, 430, 71, 22))
        self.lineEdit_16_RoundNo.setObjectName("lineEdit_16_RoundNo")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(690, 430, 53, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_DropNo = QtWidgets.QLineEdit(Form)
        self.lineEdit_DropNo.setGeometry(QtCore.QRect(770, 430, 71, 22))
        self.lineEdit_DropNo.setObjectName("lineEdit_DropNo")
        self.pushButton_Save = QtWidgets.QPushButton(Form)
        self.pushButton_Save.setGeometry(QtCore.QRect(520, 470, 93, 28))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_2_delete = QtWidgets.QPushButton(Form)
        self.pushButton_2_delete.setGeometry(QtCore.QRect(630, 470, 93, 28))
        self.pushButton_2_delete.setObjectName("pushButton_2_delete")
        self.pushButton_3_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_3_Cancel.setGeometry(QtCore.QRect(750, 470, 93, 28))
        self.pushButton_3_Cancel.setObjectName("pushButton_3_Cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "Account Type"))
        self.label_2.setText(_translate("Form", "Account Name"))
        self.label_3.setText(_translate("Form", "Address"))
        self.label_4_Postcode.setText(_translate("Form", "Postcode"))
        self.label_5_Contact_Name.setText(_translate("Form", "Contact Name"))
        self.label_6_Discount.setText(_translate("Form", "Discount %"))
        self.label_7_ACCode.setText(_translate("Form", "A/C Code"))
        self.label_8_Phone.setText(_translate("Form", "Phone"))
        self.label_9_Fax.setText(_translate("Form", "Fax"))
        self.label_10_EmailAddress.setText(_translate("Form", "Email Address"))
        self.label_11_FuelCharge.setText(_translate("Form", "Fuel Charge"))
        self.label_12_PaymentTerms.setText(_translate("Form", "Payment Terms"))
        self.label_13_VAT_RegNo.setText(_translate("Form", "VAT Reg No"))
        self.label_14_Notes.setText(_translate("Form", "Notes"))
        self.label_15.setText(_translate("Form", "Default Nominal A/C"))
        self.label_16.setText(_translate("Form", "Price Code"))
        self.label_17.setText(_translate("Form", "Account Type"))
        self.label_18.setText(_translate("Form", "Round No"))
        self.label_19.setText(_translate("Form", "Drop No"))
        self.pushButton_Save.setText(_translate("Form", "Save"))
        self.pushButton_2_delete.setText(_translate("Form", "Delete"))
        self.pushButton_3_Cancel.setText(_translate("Form", "Cancel"))
        self.database_connection()
        try:
            # Open database connection
            connection = con1.connect(user='root',
                                      password='1234',
                                      host='localhost',
                                      database='Accounts',
                                      port='3306')
            # Select all rows from the table
            with connection.cursor() as cursor:
                V1 = self.comboBox_AccountType.currentText()
                V2 = self.lineEdit_Account_Name.get()
                V3 = self.lineEdit_2_AddressLine1.get()
                V4 = self.lineEdit_3_AddressLine2.get()
                V5 = self.lineEdit_4_AddressLine3.get()
                V6 = self.lineEdit_5_Postcode.get()
                V7 = self.lineEdit_6_Contact_Name.get()
                V8 = self.lineEdit_9_Phone1.get()
                V9 = self.lineEdit_10_Phone2.get()
                V10 = self.lineEdit_11_Fax.get()
                V11 = self.lineEdit_13_FuelCharge.get()
                V12 = self.comboBox_4_AcType.get()
                V13 = self.lineEdit_15_VAT_RegNo.get()
                V14 = self.lineEdit_12_EmailAddress.get()
                V15 = self.textEdit_Notes.get()
                V16 = self.lineEdit_7_Discount.get()
                V17 = self.comboBox_2_D_N_AC
                V18 = self.lineEdit_8_ACCode.get()
                V19 = self.lineEdit_14_PaymentTerms.get()
                V20 = self.comboBox_3_PriceCode.currentText()
                V21 = self.comboBox_4_AcType.currentText()
                V22 = self.lineEdit_DropNo.get()
            sql = 'INSERT INTO NAMES (TYA, NM, A1, A2, A3, A4, CN,
TEL1, TEL2, FAX, CRL, AC, VAT, EMAIL, NOTES, VATRATE, NAC, CAT, PAYT,
PCODE, ACTYPE, DROPNO) VALUES (%s,
%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
            cursor.execute(sql, (
            V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13,
V14, V15, V16, V17, V18, V19, V20, V21, V22))
            # Commit the changes to the database
               # Close the connection

            self.connection.commit()
        finally:
            # Close the connection
            self.connection.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
