### ISSUE TITLE
Make `QtPy` modules compatible with `PySide6`/`PyQt6` import locations for `PySide2`/`PyQt5`

### ISSUE THREAD

**Issue by StSav012** [spyder-ide/qtpy#389]
Hello, everyone,

Recently, I found that `QAction` is in `QtGui` of `PySide6`, but in `QtWidgets` of `PyQt5`. Therefore, when I do `from qtpy.QtGui import QAction` having `PySide6` available, it's OK, but with `PyQt5`, I get an import error.

So, isn't it reasonable to add
```python
from PyQt5.QtWidgets import QAction
```
line into the `if PYQT5` section of `qtpy/QtGui.py` to make `QAction` available from both `QtGui` and `QtWidgets`? This would make the code more flexible. That's not the only difference between Qt5 and Qt6 modules' locations.

I see that `QtPy` tends to adhere to the `PyQt5` syntax, but this leads to such minor lacks in the universality.

Anyway, thanks for the superb tool!

**Comment by dalthviz** [comment]
Hi @StSav012 thank you for the feedback! That sounds good :+1: I think probably other classes should be added too like `QActionGroup`, `QShortcut`, `QFileSystemModel` and `QUndoCommand` (we already make those available from `qtpy.QtWidgets` for Qt6 bindings and are missing from `qtpy.QtGui` when using Qt5 bindings as well).

I would say then that we should do what you suggest, so adding the import in `qtpy.QtGui ` `QAction` in the Qt5 related sections (`if PYQT5` and probably for `if PYSIDE2`) as well for the other classes that changed from `QtWidgets` to `QtGui` on Qt6 (at least `QAction`, `QActionGroup`, `QShortcut`, `QFileSystemModel` and `QUndoCommand`).

Let us know If you want to help with this @StSav012 !

**Comment by StSav012** [comment]
Closed by https://github.com/spyder-ide/qtpy/pull/403/commits/20628845291ee37226789e61b24ad22ad8e86fac

**Comment by ccordoba12** [comment]
Since your PR hasn't been merged, this needs to remain open. Github will close the issue automatically when it is merged.

**Comment by StSav012** [comment]
https://github.com/spyder-ide/qtpy/pull/410 definitely fixes the issue. That's why I made the PR.

**Comment by CAM-Gerlach** [comment]
@dalthviz Assuming that's the case, it seems we should change the `Fixes` PR to #410, re-milestone it to v2.3.1 and update the changelog/releases page accordingly (since the issue was, then apparently solved in v2.3.1)?

**Comment by dalthviz** [comment]
Will change the title and make the issue part of v2.3.1 since the OP and general discussion here is in fact describing the changes done at #410 :+1:
