### ISSUE TITLE
Differences in QEvent subclass APIs in PyQt6 cause attribute and/or type errors

### ISSUE THREAD

**Issue by ArthurGW** [spyder-ide/qtpy#394]
For example, my application uses qtconsole, which in turns uses QtPy. At one point, qtconsole does:
```
        elif etype == QtCore.QEvent.MouseMove:
            anchor = self._control.anchorAt(event.pos())
            QtWidgets.QToolTip.showText(event.globalPos(), anchor)
```
However, when running PyQt6, the method `QMouseEvent.globalPos()` has been removed (as it has also been removed in Qt6 itself). Simply changing to call `QMouseEvent.globalPosition()` doesn't work, as the return type of that is different, `QPoint` (old) v.s. `QPointF` (new).

This is particularly annoying as most event classes used to have the same API - `pos` and `globalPos` returning `QPoint`, sometimes `posF` etc. for a floating version. Now in Python you have to do a load of type checks when you have a method that handles multiple event types. In C++ this would be spotted at compile time, which is probably why the Qt devs thought it was a reasonable change to make.

I would propose mapping this method similar to how e.g. `QFontMetrics.width` is, by monkey patching it directly onto the class object after import. i.e.:

`QMouseEvent.globalPos = lambda self: self.globalPosition().toPoint()`

There may be other missing methods, for example `QMouseEvent.pos()` doesn't actually exist in Qt6 but is defined in PyQt6 anyway - I don't know whether it exists in PySide6.

**Comment by dalthviz** [comment]
Hi @ArthurGW thank you for the feedback! That sounds like a good idea :+1: If you want to help us implementing the mappings let us know!
