### ISSUE TITLE
`QTextStreamManipulator` has no `exec` method on PyQt5/6

### ISSUE THREAD

**Issue by StSav012** [spyder-ide/qtpy#402]
In `QtCore.py`, there are several lines where `QTextStreamManipulator.exec_` is defined for PyQt5, PyQt6, and PySide6:
```python
QTextStreamManipulator.exec_ = lambda self, *args, **kwargs: self.exec(*args, **kwargs)
```
However, in neither PyQt5 nor PyQt6 has `QTextStreamManipulator.exec` or `QTextStreamManipulator.exec_` method. So, the fix-up makes no sense. So does the test part.

I'm far too lazy to dig for the origins of the lines. But still, as they don't help, should they be removed?

**Comment by CAM-Gerlach** [comment]
Looking at the [Git blame](https://github.com/spyder-ide/qtpy/blame/master/qtpy/QtCore.py#L27), seems like it was added for PyQt5 and PyQt6 in commit https://github.com/spyder-ide/qtpy/commit/13718adf22cd0b5e7d17500f9e051f8449f516af from  PR #317 for issue #316 , which mostly just added new tests related to these `exec` alias mappings, whereas it was originally added PySide6 in PR #287 to fix issue #286 and later revised in PR #308 to fix issue #305 .

I can indeed confirm `exec` nor `exec_` is present on the `QTextStreamManipulator` class object in the latest PyQt5 and 6. @dalthviz , was this added by accident, or is there a reason for this? If the latter, can it be removed?

**Comment by dalthviz** [comment]
Checking seems like those were added by accident to PyQt5/6 so yes it should be okay to remove them from the PyQt5/6 sections :+1:

**Comment by CAM-Gerlach** [comment]
Great. @StSav012 , would like like to open a PR for that?
