### ISSUE TITLE
Remove patch that “may be limited to `PySide-5.11a1` only”

### ISSUE THREAD

**Issue by StSav012** [spyder-ide/qtpy#405]
Providing https://github.com/spyder-ide/qtpy/blob/441560d192f939113689789cd2e8d5acdefb05d9/qtpy/__init__.py#L148 should lines
https://github.com/spyder-ide/qtpy/blob/441560d192f939113689789cd2e8d5acdefb05d9/qtpy/QtCore.py#L81-L84
be removed for good? Anyway, the bare `Exception` looks ugly.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting! Seems like it; on Qt 5.12 it's in `QtCore` so no bespoke import needed. Want to submit a PR?

**Comment by StSav012** [comment]
It wouldn't hurt if the code stays there several more days, right? I'd like to make some more commits in another PR first.

**Comment by CAM-Gerlach** [comment]
Sure, of course not—take your time. Thanks!
