### ISSUE TITLE
Release QtPy 2.3.1

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/qtpy#416]
I think we already have a lot of bugfixes in master which merit releasing a new version with them. And what's missing in the milestone (adding pre-commit, formatting with Black, etc) are not really blockers for this.

**Comment by CAM-Gerlach** [comment]
We should also merge #410 and #413 (closing their associated issues), since they are small and we've already approved them.

**Comment by ccordoba12** [comment]
> We should also merge https://github.com/spyder-ide/qtpy/pull/410 and https://github.com/spyder-ide/qtpy/pull/413

Sure, those are marked for 2.3.1 already.

**Comment by CAM-Gerlach** [comment]
Right, I just wanted to make sure we were on the same page about these given you'd mentioned the other things in the milestone above :+1:

**Comment by CAM-Gerlach** [comment]
SGTM, in fact I don't see a reason not to do it sooner if you have the time.

**Comment by dalthviz** [comment]
Closing this to proceed with the release!
