### ISSUE TITLE
May I please ask a question regarding licensing?

### ISSUE THREAD

**Issue by dhkimmm** [spyder-ide/qtpy#429]
Hello everyone,

I have a question regarding licensing. 
QtPy can be used by selecting PySide2,6, PyQt5,6. 
QtPy is licensed under the MIT license, while PyQt5 is licensed under the GPL license. 
I'm wondering if both the MIT and GPL licenses apply when selecting PyQt5 while importing QtPy.

Thank you.

**Comment by CAM-Gerlach** [comment]
That would be a question for a licensed attorney in your jurisdiction. I'm not one, and thus I cannot provide legal advice.

For some general background, at present, the case law is rather unclear as to whether dynamic linking in the form of importing Python packages through some intermediate package actually invokes the GPL; however, if you're actually shipping PyQt5 with your application, then it likely does. If your application can run under either PySide or PyQt, which the user selects, then in that case it would likely not be considered a derivative work. However, if your application can only run under PyQt, then there's a decent chance it does. If your work is FOSS, its not likely to be a big issue in practice, but we certainly cannot state definitely that it won't be.

Again, I encourage you to consult a qualified lawyer in your jurisdiction who can provide you with proper legal advice for your jurisdiction.

Best of luck!
