### ISSUE TITLE
Add compatibility layer for keywords arguments of `QFileDialog ` `get*` class methods

### ISSUE THREAD

**Issue by Czaki** [spyder-ide/qtpy#432]
The `QfileDialog` class contains few static methods for fast opening files: https://doc.qt.io/qt-6/qfiledialog.html#static-public-members

Unfortunately, PyQt and PySide backends differ in the naming argument that provides default directory. 
In PyQt5/6 it is named `directory`, when in PySide2/6 it is named `dir`. PySide follows original Qt convention where PqYt decided to not use the keyword as name of an argument.

Unfortunately, I do not know the method of testing that could find this problem. AS calling this function opened dialogs that hang tests, and with mocking the problem with the signature is not triggered. 

Are you open for PR that will introduce cross-compatibility layer. 

Something like:

```python
if "dir" in kwargs:
    kwargs["directory"] = kwargs.pop("dir")
```

and vice versa? 

inspired by discussion from https://github.com/napari/napari/pull/5834

**Comment by dalthviz** [comment]
Hi @Czaki thank you for the feedback! I think that makes sense to improve the situation here with the `QFileDialog` :+1:

Thinking about this, not totally sure but, maybe this is already covered by the wrapper function we have for the `QFileDialog` at:

https://github.com/spyder-ide/qtpy/blob/1874fbac7ea6c56eb6de58d7d8dceae5229644e0/qtpy/compat.py#L82-L102

And the respective functions for the static methods like for example `getSaveFileName` at:

https://github.com/spyder-ide/qtpy/blob/1874fbac7ea6c56eb6de58d7d8dceae5229644e0/qtpy/compat.py#L129-L138

?

Let us know if the current wrapper definition helps or if some modification needs to be done and of course happy to see a PR if that is the case!

**Comment by Czaki** [comment]
This wrapper looks to solve the problem, but I need to figure out the discoverability of this feature as many people may use only Qt/PySide documentation and do not find the compact module.

**Comment by hmaarrfk** [comment]
One aspect in which the provided wrappers are not feature complete is when applications wish to customize the user experience such as with the "history"

napari uses:

```
dlg = QFileDialog()
hist = get_save_history()
dlg.setHistory(hist)

filename, selected_filter = dlg.getSaveFileName(
    parent=self,
    caption=trans._('Save {msg} layers', msg=msg),
    directory=hist[0],  # home dir by default,
    ....
)
```

which requires:

1. The use of the method `setHistory`
2. a common interface for `directory` vs `dir`

Maybe I am missing one aspect of the compat module, but I didn't see a clear way of getting there from browsing the source of the `compat.py` module.

**Comment by Czaki** [comment]
I have created #433 which may be a proper solution. There are currently no tests so it is marked as a draft but I would like to hear what did you think about this.

**Comment by dalthviz** [comment]
Thanks for the feedback and proposing a solution! To be honest I'm not totally sure what could be the best here 🤔, what do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
I took a quick look to @Czaki's PR and I think it's a good idea because it'd make things consistent between PyQt and PySide.
