### ISSUE TITLE
 qtpy.uic.loadUiType failing for PySide6 

### ISSUE THREAD

**Issue by JaRoSchm** [spyder-ide/qtpy#439]
Hi, while trying to use vitables after an upgrade to PySide6 I noticed that `qtpy.uic.loadUiType` is failing:
```
  File "/home/jschmidt/mambaforge/envs/CPG_stable/lib/python3.11/site-packages/vitables/vtwidgets/renamedlg.py", line 63, in <module>
    loadUiType(os.path.join(os.path.dirname(__file__), 'rename_dlg.ui'))[0]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jschmidt/mambaforge/envs/CPG_stable/lib/python3.11/site-packages/qtpy/uic.py", line 278, in loadUiType
    compileUi(fd, code_stream, indent=0, from_imports=from_imports)
    ^^^^^^^^^
NameError: name 'compileUi' is not defined. Did you mean: 'compile'?
```
This seems to be a bug in qtpy as `compileUi` is indeed only imported in the PySide2 branch of the imports. Or shouldn't `loadUiType` be used with PySide6?

I'm using (installed from conda-forge):
Python 3.11.4
qtpy 2.3.1
PySide6 6.5.1 
vitables 3.0.2

**Comment by dalthviz** [comment]
Hi @JaRoSchm thank you for the feedback! Checking a little bit I think we are [missing to import `loadUiType` for PySide6](https://doc.qt.io/qtforpython-6/PySide6/QtUiTools/loadUiType.html)! and the current custom implementation should only be used for PySide2 indeed.

Would you like to help us adding the missing import, moving the loadUiType function inside the PYSIDE2 validation and checking locally if that helps?

Let is know!

**Comment by JaRoSchm** [comment]
Thanks I will look into that!
