### ISSUE TITLE
`qtpy` compatibility problem with `qtwidgets` + `pyinstaller`

### ISSUE THREAD

**Issue by el07694** [spyder-ide/qtpy#441]
pip install qtpy qtwidgets #fro animated toggle switch checkbox
pyinstaller my_app.spec
run the .exe:
Error: ImportError: DLL load failed (in line: from PyQt5 import QtWidgets, QtCore, QtGui)

pip uninstall qtpy qtwidgets
pyinstaller my_app.spec
run the exe:
NO ERROR

I think this error is not related with qtwidgets modules because i manually installed with different module name.
So it's a compatibility error with PyQt5 and qtpy.

How can i solve this?

**Comment by dalthviz** [comment]
Hi @el07694 thank you for the feedback! Could you check your PyQt5 installation? What happens when you try to run something like `import PyQt5` in your current env/setup? Let us know!

**Comment by el07694** [comment]
Thanks for the reply.

The PyQt5 module works fine.

I solve the problem by uninstalling qtpy and replacing qtpy imports with
PyQt5.* accordingly. Then i rename the module as extra_widgets (instead of
widgets) and then the pyinstaller command run with no error message.

Best regards,
Chris Pappas

Στις Πέμ 20 Ιουλ 2023 στις 9:14 μ.μ., ο/η Daniel Althviz Moré <
***@***.***> έγραψε:

**Comment by dalthviz** [comment]
Sorry for the late reply and thank you for the new info @el07694 ! Seems like then something was happening with qtpy + pyinstaller + qtwidgets + some naming conflict (using `widgets`). I checked locally I'm able to use qtpy + qtwidgets 🤔. I think there is not much to do from the QtPy side so I'm closing this but if you have any other info let us know!
