### ISSUE TITLE
Some compatibility issues when using latest PyQt6 or PySide6 (6.5+)

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#442]
Checking around seems like the latest version of the Qt 6 bindings (6.5.2 I think) come with some changes (related with deprecations) that can cause some errors. Some examples:

* https://github.com/napari/napari/issues/6060
* https://github.com/napari/napari/issues/6135
* https://github.com/napari/napari/pull/5986#issuecomment-1669867592 (`Qt.ItemFlags` vs `Qt.ItemFlag` - PyQt6)
* https://github.com/jupyter/qtconsole/issues/583#issuecomment-1670130291 (`QDragMoveEvent.pos` vs `QDragMoveEvent.position`)

I think it could be worthy to check if something from the QtPy side could be done and include it in v2.4.0. Also, testing on the CI with Qt 6.5 seems worthy and could help us see if there are any other errors/changes to be done.

Other relevant related work in progress: 

* https://github.com/spyder-ide/spyder/pull/21227#issuecomment-1668211205

What do you think @ccordoba12 @CAM-Gerlach ?

**Comment by ccordoba12** [comment]
If we can help to provide more compatibility with Qt6, I'm ok with it.
