### ISSUE TITLE
Try to retrieve `QT_API` from file if not set in env variable 

### ISSUE THREAD

**Issue by ZeeD** [spyder-ide/qtpy#452]
The current logic of `qtpy` is to let the consumer set `QT_API` to explicitly set a library to use, or let the internal rules guess what to do.

While useful, it's a bit cumbersome for me to set the env variable for the run, and I would prefer to be able to write the library in a configuratin file (it's not important the name of the file per se, `.env`, `~/.config/qtpy`, `qtpy.conf` or anything will do).

The env variable should "win", but if not set, before using the internal rules, I would like `qtpy` to look for the library to wrap in this config file

**Comment by dalthviz** [comment]
Hi @ZeeD thank you for the feedback! So you mean that the we should have a way to set the `QT_API` via a user defined configuration file and the priority for getting the `QT_API` value should be:

1. Environment variable value
2. Config file
3. Fallback logic to guess which bindings are available

What do you think @ccordoba12 @CAM-Gerlach ?

**Comment by ccordoba12** [comment]
I don't like this idea because we'd be complicating things for not a very strong reason:

> While useful, it's a **bit** cumbersome for me to set the env variable for the run, and I would prefer to be able to write the library in a configuratin file

QT_API can be easily set before loading `qtpy` in your the main Python file of your app. So, unless the case for this idea is made really compelling, I'm -1 on it.

**Comment by ZeeD** [comment]
well, I (and some linters I use) don't really like to mix `import`s and messing with `os.environ`.

FWIW my current solution is to have a `FORCE_QT_API_TO_PYSIDE6.pth` in my venv's `site-packages`, with just `import os; os.environ['QT_API'] = 'pyside6'` as content

**Comment by ccordoba12** [comment]
> well, I (and some linters I use) don't really like to mix imports and messing with os.environ.

Those warnings can be easily ignored with `# noqa`. So, I'd say the case is really not strong.

**Comment by ZeeD** [comment]
YMMV, but while linters can be shut down via `# noqa` my lizard brain cannot :/
Again, my preferred solution is to relies on python initialization customizability

But fair enough... I'll close this ticket then

**Comment by ccordoba12** [comment]
Ok, thanks for understanding.
