### ISSUE TITLE
Typo causes failed QWebEngineScript with PySide6

### ISSUE THREAD

**Issue by cafeclimber** [spyder-ide/qtpy#458]
As the title says, `QWebEngineScrip` should be `QWebEngineScript`

https://github.com/spyder-ide/qtpy/blob/540fe7e560168e3ba27c17f6e423ac5f0b27620c/qtpy/QtWebEngineWidgets.py#L67

**Comment by dalthviz** [comment]
Hi @cafeclimber thank you for the feedback! I think this has been recently fixed by PR #455 . The fix will be available in the next QtPy release (2.4.1). I will link this issue with #455 and mark it as part of the v2.4.1 milestone for future reference :+1:

**Comment by tghw** [comment]
This is a complete breaker for Pyside6 and has been over a month since filed. Any chance we could get a release to fix this issue sooner?

**Comment by dalthviz** [comment]
Hi @tghw thank you for the feedback! I think that seems reasonble, we will try to do a bug fix release (2.4.1) soon  :+1:

**Comment by tghw** [comment]
@dalthviz Thanks!

For anyone who comes across this in the meantime, monkey patching the `PySide6.QtWebEngineCore` module with the typo'd name does work, but it's an ugly fix.
