### ISSUE TITLE
BUG: Incompatible with PySide6 6.7.0

### ISSUE THREAD

**Issue by larsoner** [spyder-ide/qtpy#477]
6.7.0 just released today, using this code:
```
from qtpy import API
from qtpy.QtWidgets import (
    QFileDialog,
    QApplication,
    QWidget,
)
assert API == "pyside6", f"{API=}"

QApplication([])


class A(QFileDialog):
    def __init__(self):
        super().__init__(None)

print(isinstance(QFileDialog(), QWidget))
print(isinstance(A(), QWidget))
```
on 6.6.3.1 I get the expected:
```
True
True
```
but on 6.7.0 I get:
```
False
False
```
and if I change the import at the top to be `from PySide6.QtWidgets` things are again fine, so something is broken with qtpy specifically.

**Comment by larsoner** [comment]
Okay this is some very weird upstream bug, this code fails on 6.7.0:
```
from PySide6.QtGui import QActionGroup
from PySide6.QtWidgets import *

QApplication([])
assert isinstance(QFileDialog(), QWidget)
```
if you comment out the `QActionGroup` import or move it after the star import things are fine.

**Comment by ccordoba12** [comment]
So, do you think this is an issue with qtpy or PySide6?

**Comment by larsoner** [comment]
PySide6, I opened https://bugreports.qt.io/browse/PYSIDE-2674 upstream. I tried messing with the import order in `qtpy` to work around the issue but couldn't, so I'll close!
