### ISSUE TITLE
QtMultimedia support

### ISSUE THREAD

**Issue by davvid** [spyder-ide/qtpy#49]
The following does not seem to work with QtPy:

```
from qtpy import QtMultimedia
```
but it does work if we import QtMultimedia directly from either PyQt4 or PyQt5.

Would it be desirable to provide a wrapper over QtMultimedia and QtMultimediaWidgets?

Are there any gotchas?

**Comment by ccordoba12** [comment]
Yes, please open a PR to add `QtMultimedia` as a supported module :-)
