### ISSUE TITLE
Cannot import name 'pyqtSignal' from 'qtpy.QtCore'

### ISSUE THREAD

**Issue by doronbehar** [spyder-ide/qtpy#492]
Hey, I'm trying to make a PyQt5 app be compatible with both PyQt6 and PyQt5, and I get the error in the title of the issue. Is this intentional? I saw a very old issue related to this:

https://github.com/spyder-ide/qtpy/issues/76

But it seems resolved...

**Comment by ccordoba12** [comment]
Hey @doronbehar, you need to import `Signal`, not `ptqtSignal`. That's the convention we in Qtpy.

**Comment by doronbehar** [comment]
Thanks and sorry for the late reply, and for not reading the README :).
