### ISSUE TITLE
Add PYQT5 / PYQT4/PYSIDE boolean variables

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/qtpy#5]
Spyder has a number of global variables for convenience to check whether we are running on PyQt5, PyQt4 or PySide.
It would be nice if those were moved to qtpy. I think that anyone using qtpy could use those.

**Comment by ccordoba12** [comment]
I agree. The idea for Spyder 3.0 beta3 is to remove its own shim and start using qtpy instead, so we *need* to do this.
