### ISSUE TITLE
Hijacked PyQt types are not returned from native Qt APIs

### ISSUE THREAD

**Issue by ivany4** [spyder-ide/qtpy#502]
QtPy 2.4.2 has integrated this PR: https://github.com/spyder-ide/qtpy/pull/461, which swaps `QToolbar` and `QAction` types with custom subclasses. This introduced a new problem that instances returned from Qt no longer pass instance checks.

E.g.:

```python
from qtpy import QtWidgets

app = QtWidgets.QApplication([])
window = QtWidgets.QMainWindow()
new_toolbar = window.addToolBar('Toolbar title')
assert isinstance(new_toolbar, QtWidgets.QToolBar)
```

This will pass in QtPy 2.4.1 and will fail with QtPy 2.4.2. It now requires to check against true PyQt classes, e.g. ` assert isinstance(new_toolbar, PyQt5.QtWidgets.QToolBar)`

By extension, returned instances will have different behavior from the manually created ones

**Comment by dalthviz** [comment]
Hi @ivany4 thank you for the report and sorry for the late reply! We will revert the wrapper changes to prevent such errors and inconsistencies!
