### ISSUE TITLE
Breaking change related to QMenu in 2.4.2

### ISSUE THREAD

**Issue by astrofrog** [spyder-ide/qtpy#505]
Prior to QtPy 2.4.2, the following:

```python
from qtpy.QtWidgets import QApplication, QMenu

app = QApplication([])

menu = QMenu()
menu.addMenu('test')

submenu = menu.children()[1]

print(isinstance(submenu, QMenu))
```

would return ``True``, but now returns ``False`` because the class for menus added using ``addMenu`` is the native QMenu class whereas QtPy now exposes a wrapped class. Fixing this might be a matter of overriding ``addMenu``?

**Comment by axel-kah** [comment]
This issue hit us by surprise as well and broke our application in a very interesting way. Maybe the implications were not apparent at the time, but at least in hindsight, introducing these wrapper classes seems to break fundamental Qt functionality (eg. [`Qbject.findChild()` et. al](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QObject.html#PySide2.QtCore.PySide2.QtCore.QObject.findChild)) and should have been handled like a major change.

The change in question seems to have been introduced with https://github.com/spyder-ide/qtpy/pull/461

Would be great to get some guidance on how to deal with the situation. Will this change be rolled back or is there advice on how to make `findChild()` work again?

**Comment by dalthviz** [comment]
Hi @astrofrog thanks for the report! I think as @axel-kah mentions we could revert adding those wrappers (I though they were necessary but after some checks seems like that is not the case). Working on it over #507 ! If you have further thoughs about this let me know!
