### ISSUE TITLE
Add to the readme the importance of qtpy when migrating an application

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtpy#62]
This has to be the greatest strength of this project, yet we do not say anything about it on the readme.

We should give a small description on its importance.

**Comment by ccordoba12** [comment]
We could link to the `git-cola` issue that talked about this, for example :-)

**Comment by goanpeca** [comment]
Sure, like a 

Success stories:
- [git-cola]()

**Comment by CAM-Gerlach** [comment]
I can try to address this, but @dalthviz or @ccordoba12 could you explain a little more what's the intent here? When migrating an application to...what, exactly? A specific binding/other wrapper to QtPy? Porting to newer Qt/binding versions? Something else? A little more detail would be helpful to know what we're looking for here.

**Comment by ccordoba12** [comment]
> A specific binding/other wrapper to QtPy?

Yes.

**Comment by CAM-Gerlach** [comment]
I see @ccordoba12 , so is the "greatest strength" cited the ease of migrating _to_ QtPy (relative to...something)? I'm still a little unclear; maybe its just phrased oddly but the issue title and minimal information present is rather confusing.

The git-cola issue you mention above would be very useful here, but the link just points to this issue and while I spent some time Googling it, I didn't find anything that was obviously what this was referring to, though it didn't help that it wasn't entirely clear what I should be looking for,

**Comment by ccordoba12** [comment]
> strength relative to...what, specifically

Forgetting about the Python bindings (PyQt vs PySide) and version of them (5 vs 6) you're using. Your application should work with any of them if you're using QtPy.

> The git-cola issue you mention above would be very useful here, but the link just points to this issue and while I spent some time Googling it, I didn't find anything that was obviously what this was referring to

It should be in the project's git history.

**Comment by CAM-Gerlach** [comment]
Okay, thanks. There were 71 issues and 45 commits that contained "QtPy", many of them about various binding compatibility issues and bugs with QtPy, but my best guess is that git-cola/git-cola#232 is the one you're implying. Is that correct?

**Comment by ccordoba12** [comment]
Yeah, sounds right.

**Comment by CAM-Gerlach** [comment]
Thanks, I'll give it a shot.

**Comment by CAM-Gerlach** [comment]
Glue also mentions this in [their docs](http://docs.glueviz.org/en/stable/developer_guide/qt_development.html#using-qtpy)

**Comment by dalthviz** [comment]
While checking maybe is worthy to add a section to the `README.md` listing projects that use QtPy (like for example `glue`, `git-cola`). What do you think @ccordoba12 @CAM-Gerlach ?

**Comment by CAM-Gerlach** [comment]
I think that's a great idea. A lot of projects have to be using it (or at least a lot of projects that have many deps), given the PyPI download numbers. Though I think a lot of those are driven by something with the Linux distros, possibly on servers and VMs and such.

**Comment by CAM-Gerlach** [comment]
That said, if it'll delay PR #301 its probably better if we just merge that and then I take care of it in my other docs PR since that's a de-facto blocker due to the likelihood of merge conflicts.

**Comment by ccordoba12** [comment]
> I think that's a great idea

I agree with @CAM-Gerlach.
