### ISSUE TITLE
Add documentation for how to run tests

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtpy#66]
How is this normally handled? should we add an environment.yaml to set a full environment for qtpy? or should we add a specfile/requirements-test.txt file?

@ccordoba12, @Nodd?

**Comment by ccordoba12** [comment]
An environment.yaml along with some instructions in our README would be fine for me :-)

**Comment by goanpeca** [comment]
sure that would work :-)

**Comment by jitseniesen** [comment]
I just wrote http://github.com/spyder-ide/spyder/wiki/Dev%3A-Testing for the spyder repo - maybe you can use it as a starting point?

**Comment by CAM-Gerlach** [comment]
This has been changed and simplified significantly following PR #262 . I was already planning to add a Contributing Guide as following the mold of an updated, simplified and more helpful standardized version of the Spyder one, which would cover this, so I'll take care of this soon.
