### ISSUE TITLE
Auto generate methods that have been deprecated for Qt5 stuff

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtpy#68]
We need to generate all the things that change between qt4 and qt5 and try to trun them into issues so we can start working on this issues little by little.

**Comment by mottosso** [comment]
We're on the same road! :)

- https://github.com/mottosso/Qt.py/issues/105

Working on this now, let's solve this!

**Comment by goanpeca** [comment]
Hi @mottosso, what do you propose?

**Comment by goanpeca** [comment]
Our needs are based on patches like this

https://github.com/spyder-ide/qtpy/blob/master/qtpy/_patch/qheaderview.py

That will include missing methods (on older libraries Qt4...) and include newer methods (renames) and if possible to offer the new functionality (this will not always be possible).

I generally use the Qt docs for everything, I really never bothered looking at pyside or pyqt, so all the info I got regarding methods I scrapped from the Qt docs website (for the different versions of Qt5) and then made the set arithmetic locally.

**Comment by mottosso** [comment]
> Our needs are based on patches like this

Woah, I can't tell what's going on in that file. :O

> Hi @mottosso, what do you propose?

I was going to give this a try.

1. During a Travis build, automatically generate a dictionary of members and argument signatures of everything in the `PySide2` namespace
2. Compare this with an identical listing for each other binding
3. Things that exist in PySide2, but not in the others, are officially *missing* from other bindings; and that's a bug.

Using the Qt documentation site is another option. Scraping it. At the moment, there's tension about whether to commit to PySide2 completely, or the official Qt docs. The problem with PySide2 being that it is as of yet incomplete.

What do you think?

**Comment by goanpeca** [comment]
Your method is ok but was incomplete for our requirements.

That's exactly how I started (some weeks ago) but then realized I needed to know what was the actual truth, and that can only be provided by the Qt docs.

We can not say who is right if PySide2 or PyQt5, but we are pretty sure Qt docs are right and we aim for that first and then we will handle whatever strange things PyQt5 or PySide2 needed to implement (a simple example is `Signals` and `Slots`, that differs in PyQt and PySide, but we Actually use the PySide convention).

The previous example needs to be documented cause it is indeed a quirk of this library cause it is the most obvious example where we do not follow PyQt5 http://pyqt.sourceforge.net/Docs/PyQt5/signals_slots.html

**Comment by mottosso** [comment]
> That's exactly how I started (some weeks ago) but then realized I needed to know what was the actual truth, and that can only be provided by the Qt docs.

Perfect! This will save us lots of time.

Do you remember which commit/PR this was? I'd love to take a look at the approach.

How do you feel about fetching members and argument signatures directly from the Qt git repository?

**Comment by ccordoba12** [comment]
> How do you feel about fetching members and argument signatures directly from the Qt git repository?

I think that should be the way to go :-)

**Comment by goanpeca** [comment]
Sure, that works, I just happen to like scrapping stuff :-p and not parsing c++ code

**Comment by mottosso** [comment]
About your previous attempt at this, I was looking through your past PR's but came up empty. Do you remember where this went? It would be very helpful!

**Comment by mottosso** [comment]
Ok, we've got a first pass on this!

- https://github.com/mottosso/Qt.py/pull/120

This does as I mentioned above; comparing members of other bindings to PySide2. It's possible the same achieved by PySide2 switched out for PyQt5, which may be closer to what you guys need.
