### ISSUE TITLE
Inject itself into sys.modules for other PyQt versions

### ISSUE THREAD

**Issue by kernc** [spyder-ide/qtpy#77]
Scenario:

In my app, I `from qtpy.QtCore import Qt`. I run my app with `QT_API=pyqt5`, so PyQt5 is preferred, defaulting to PyQt4 if the former is not available. Anyway, PyQt5 is available and my app runs fine.

In some obscure module, or in a stand-alone add-on for my app, I rely on a third-party Python package that imports and works with PyQt4. The import fails. My app breaks.

Use case:

I would like like qtpy to inject itself into `sys.modules` so that any requests for objects from PyQt4 are resolved, _best effort_, from qtpy.

**Comment by kernc** [comment]
Some justification (basically above scenario reiterated) in https://github.com/biolab/orange3/issues/1613#issuecomment-250332359.

**Comment by ccordoba12** [comment]
I don't understand too well your request. Could you create a pull request to better understand what you need? Thanks :-)

**Comment by brylie** [comment]
For context, @kernc described the request in [the linked issue](https://github.com/biolab/orange3/issues/1613#issuecomment-250332359) as:

> Orange depends on lots of third-parties and has add-on, not all can be expected to keep up with pace. If PyQtGraph didn't yet work with PyQt5 or if some other package we depend on, like a simple package containing a QRangeSlider widget, or whatever, hasn't yet been updated to work with PyQt5, we would be barred from trying PyQt5 lest we fork and patch everything. Anyway, it just seems a reasonable thing to expect from an abstraction layer to convenience apps that import modules that import from some other version of PyQt if this can be achieved without much effort. AnyQt does this, I think. So all the add-ons and third-parties remain to work, at least to a significant degree.
>
> --@kenrc

**Comment by ccordoba12** [comment]
Sure, I read that :-) I just don't understand how he expects `qtpy` to be injected into `sys.modules`.

A pull request with that and a simple test of a file trying to import PyQt4 would be the best way to understand what he wants.

**Comment by brylie** [comment]
@ccordoba12 cool. Thanks for your quick responses.

**Comment by Nodd** [comment]
I don't think it's possible to import both PyQt4 and PyQt5. You can't simply replace PyQt4 by qtpy either, since qtpy uses Qt5 module layouts. If a module needs PyQt4, then you have to use it no matter what. I don't understand how using `sys.modules` would make things work here.

**Comment by kernc** [comment]
Exactly. Depending on set `QT_API`, qtpy would adapt its exposed interface. The most major difference, to my viewing, is distinction of QtGui and QtWidgets anyway. Something like:
```py
if QT_API == 'pyqt4':
    qtpy.QtGui.__dict__.update(qtpy.QtWidgets.__dict__)
    sys.modules['PyQt4'] = qtpy
    sys.modules['PyQt4.QtGui'] = qtpy.QtGui
```
I think best-effort compatibility could be achieved in not too many lines.

**Comment by goanpeca** [comment]
Sorry I still don't understand

>In some obscure module, or in a stand-alone add-on for my app, I rely on a third-party Python package that imports and works with PyQt4. The import fails. My app breaks.

This is not fixing the fact that you third party app is only Qt4 compatible and wont work with a Qt5 app. If you rely on a third party app that is not Qt5 compatible, then you need to vendor it or fork it, or the third party app needs to offer Qt5 support somehow (with their own shim or via qtpy).

**Comment by kernc** [comment]
In my experience, most PyQt4 uses are out-of-the-box compatible with PyQt5 (with something like [above short snippet](https://github.com/spyder-ide/qtpy/issues/77#issuecomment-250452329)). Review the [differences between Qt4 and Qt5](https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5). In a normal, not too complex Qt app, few present a barrier as strong as a separate QtWidgets module. We are doing this already with great success. :smiley:

**Comment by goanpeca** [comment]
I personally don't endorse messing up the with the sys modules in such a way, its a clever hack and might work, but the purpose of QtPy was to gradually allow Qt Python apps to make their code Qt5 compatible in a way that the code moved to the future (unlike what Python2/3 allowed because of its change in syntax).

>We are doing this already with great success. 😃

Cool, if the approach works for you, but as stated this is definitely not the intent of this shim 😉.

**Comment by kernc** [comment]
Of course, the proposed wouldn't _prevent_ anyone from upgrading to PyQt5 or later. It just wouldn't force them to at any cost.

**Comment by goanpeca** [comment]
>It just wouldn't force them to at any cost.

But leaving the the code unchanged is not really upgrading to Qt5, its just making a clever hack, hence not really endorsing this change.

**Comment by kernc** [comment]
Some projects are big and/or temporarily stalled due to lack of time.

Suppose we would like to _test_ our app with PyQt6 as soon as it is released (6.1 or something). We would first need to wait for all our dependencies to acknowledge and update their code to import from PyQt6. Or fork them. Neither of which is too reasonable. Some projects are temporarily stalled or efforts dedicated elsewhere. Of course, if they are completely unmaintained and don't ever intend to upgrade, that's another issue.

Yet even with them, you wrapper would still work 95% of the time.

**Comment by goanpeca** [comment]
I understand all your concerns, but this is out of the scope.

As a side note I would be wary of depending on projects/libraries that are `temporarily stalled or efforts dedicated elsewhere`.

We will be the first to update our library to make sure that the same principles that once made sense for Qt5 make sense for Qt6 when it arrives, so any library already using qtpy would benefit from qtpy 2.0 (what I believe would be the name for the version supporting Qt6)

**Comment by Nodd** [comment]
A big difference between Qt4 and Qt5 is the new QtWidget module. How would any Qt4 work with this change ?

**Comment by goanpeca** [comment]
I think he meant

```
if QT_API == 'pyqt4':
    qtpy.QtGui.__dict__.update(qtpy.QtWidgets.__dict__)
    sys.modules['PyQt4'] = qtpy
    sys.modules['PyQt4.QtGui'] = qtpy.QtGui
```

**Comment by ccordoba12** [comment]
@kernc, I can see the value of your clever hack :-)

Please create a pull request with it, but make it optional, i.e. find a way to apply it only if library authors want to use it :-)

**Comment by kernc** [comment]
You mean optional in a way such that qtpy library _users_ can decide if they want to enable it, like:
```py
# Somewhere at the beginning of an app
# and before any other PyQt loaded ...
import qtpy
qtpy.enable_compatibility()  # for lack of a better name
```
Will be happy to!

**Comment by ccordoba12** [comment]
Yep, that's exactly what I meant :wink:

**Comment by goanpeca** [comment]
@kernc any updates :-p ?

**Comment by goanpeca** [comment]
Lack of response
