### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by innerhippy** [spyder-ide/qtpy#80]
There's a bunch of missing classes on QtGui:
```
QApplication, QFileIconProvider, QItemDelegate, QHBoxLayout,
QVBoxLayout, QDialog, QLineEdit, QLabel, QSizePolicy, QDialogButtonBox, 
QLayout, QSpinBox, QDoubleSpinBox, QListView, QTreeView, QCompleter,
QTableView, QAbstractItemView, QPushButton, QDirModel, QSplitter,
QHeaderView, QFileDialog, QGridLayout, QAbstractItemDelegate
```

Some of these seem to be quite fundamental classes, so was wondering why they are not included.

Thanks!

**Comment by ccordoba12** [comment]
They are included in `QtWidgets`. The purpose of this package is to develop applications as if you were using PyQt5, not PyQt4.

Please read our README for a more detailed explanation :-)
