### ISSUE TITLE
Allow QtPy to work without session support

### ISSUE THREAD

**Issue by astrofrog** [spyder-ide/qtpy#81]
At the moment, QtPy crashes completely if used with the latest PyQt4 build from conda-forge:

https://github.com/conda-forge/pyqt-feedstock/issues/5

I wonder if we could make QtPy more tolerant of cases where session support is not enabled, by putting the session-related imports inside a try/except?

**Comment by ccordoba12** [comment]
That's a problem I need to solve in the Qt build of conda-forge, not for `qtpy` to do something about it :-)

**Comment by astrofrog** [comment]
Ok no problem - just wasn't sure if the Qt fix would take a while if it was complex.

**Comment by ccordoba12** [comment]
I'm on vacations right now but I'll work on it next week.

The fix is not that hard (as far as I can tell), just a matter of installing the right Xorg libraries before compiling Qt in the conda-forge docker image.

And after that, I also need to rebuild PyQt.
