### ISSUE TITLE
you should add QIcon to QtWidgets...

### ISSUE THREAD

**Issue by malliwi88** [spyder-ide/qtpy#82]
Hi

I think this a function escaped in the hierarchy from QtGui, because I can call this using
```python
from qtpy.QtGui import *
```

but not

```python
from qtpy.QtWidgets import (QIcon)
```

I think this is a minimal issue (depends your implementation), but it's contribute to improve order ;).

Thanks

**Comment by ccordoba12** [comment]
QICon is part of QtGui in Qt5:

http://doc.qt.io/qt-5/qicon.html

and the purpose of `qtpy` is to follow the Qt5 library layout.

So I don't understand too well the purpose of your request :-)
