### ISSUE TITLE
Include core doc files in PyPi releases

### ISSUE THREAD

**Issue by toddrme2178** [spyder-ide/qtpy#83]
The version of QtPy on PyPi lacks the `AUTHORS.md`, `CHANGELOG.md`, `LICENSE.txt`, and `README.md`.  The lack of the license in particular is a problem for downstream packagers.  Could you please include these in the upcoming bugfix release?

**Comment by goanpeca** [comment]
We will :-)

**Comment by toddrme2178** [comment]
Thanks!
