### ISSUE TITLE
QDesktopServices split into QDesktopServices and QStandardPaths

### ISSUE THREAD

**Issue by melevine** [spyder-ide/qtpy#89]
The QDesktopServices from Qt4 has been split into two namespaces, QDesktopServices and QStandardPaths, but there is no support for QStandardPaths in QtPy.  I would expect QtPy to support code like:

`home_location = QtCore.QStandardPaths.standardLocations(QtCore.QStandardPaths.HomeLocation)`

Qt4 API
http://doc.qt.io/qt-4.8/qdesktopservices.html

Qt5 API
http://doc.qt.io/qt-5/qdesktopservices.html
http://doc.qt.io/qt-5/qstandardpaths.html

**Comment by ccordoba12** [comment]
Could you create a pull request with this change? Thanks!

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.

**Comment by phargogh** [comment]
Hey everyone, when I `pip install "qtpy>1.3"` and set `QT_API=pyqt4`, the only attributes available in the  `QtCore.QStandardPaths` module are the data attributes for the locations the class/enum `StandardLocation` and `displayName(...)`.  Other methods defined by QStandardPaths are missing, most notably the methods that are really helpful for transforming standard paths to actual paths such as `QtCore.QStandardPaths.writableLocation(...)`.

The temporary workaround is to `pip install "qtpy<1.3"`.

To reproduce, compare:
* `QT_API=pyqt4 python -c "from qtpy import QtCore; help(QtCore.QStandardPaths)"`
* `QT_API=pyqt5 python -c "from qtpy import QtCore; help(QtCore.QStandardPaths)"`

**Comment by ccordoba12** [comment]
@phargogh, please open a new issue about it.
