### ISSUE TITLE
Anaconda Spyder Keyboard input error

### ISSUE THREAD

**Issue by eedreamer** [spyder-ide/qtpy#99]
I am using tightVNC to access my server. On the server, I installed anaconda spyder and the standalone spyder respectively. The anaconda spyder has the problem to show the correct keyboard response, but the standalone spyder works just fine.
Ubuntu Linux: 16.04
Anaconda 2.7.13 :: Anaconda 4.2.0 (64-bit) | Spyder: 3.1.2 | 
Qt version 5.6.2

Error Log for theAnaconda Spyder Launch
Qt: XKEYBOARD extension not present on the X server.
Fontconfig error: Cannot load default config file.

I did some research. I think the qt module messed up the keyboard mapping, which makes the anaconda spyder not responding correctly the keyboard type ins.

Please check and help.
Thanks

**Comment by ccordoba12** [comment]
This has nothing to do with qtpy.
